// src/pages/nft/profile-setting.vue
<template>
    <div>
        <NftNavLight/>

        <section class="bg-half-170 d-table w-100" :style="{backgroundImage:`url(${bg})`}">
            <div class="bg-overlay bg-gradient-overlay"></div>
            <div class="container">
                <div class="row mt-5 justify-content-center">
                    <div class="col-12">
                        <div class="title-heading text-center">
                            <h5 class="heading fw-semibold mb-0 sub-heading text-white title-dark">Profile Setting</h5>
                        </div>
                    </div>
                </div>

                <div class="position-middle-bottom">
                    <nav aria-label="breadcrumb" class="d-block">
                        <ul class="breadcrumb breadcrumb-muted mb-0 p-0">
                            <li class="breadcrumb-item"><router-link to="/">Coral</router-link></li>
                            <li class="breadcrumb-item"><router-link to="/creators">Creators</router-link></li>
                            <li class="breadcrumb-item"><router-link to="/creator-profile">@StreetBoy</router-link></li>
                            <li class="breadcrumb-item active" aria-current="page">Profile Setting</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </section>

        <div class="position-relative">
            <div class="shape overflow-hidden text-white">
                <svg viewBox="0 0 2880 48" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M0 48H1437.5H2880V0H2160C1442.5 52 720 0 720 0H0V48Z" fill="currentColor"></path>
                </svg>
            </div>
        </div>

        <section class="section">
            <div class="container">
                <div class="row">
                    <div class="col-lg-9">
                        <h5>You can set preferred display name, create your branded profile URL and manage other personal settings.</h5>
                    </div>
                </div>
                <div class="row g-4">
                    <div class="col-lg-4 col-md-5 col-12">
                        <div class="profile-pic">
                            <input id="pro-img" name="profile-image" type="file" class="d-none" @change="handleChange($event)" />
                            <div class="position-relative d-inline-block">
                               <img :src="image" class="avatar avatar-medium img-thumbnail rounded-pill shadow-sm" id="profile-image" alt="">
                                <label class="icons position-absolute bottom-0 end-0" for="pro-img"><span class="btn btn-icon btn-sm btn-pills btn-primary"><i data-feather="camera" class="icons"></i></span></label>
                            </div>
                        </div>

                        <div class="mt-4">
                            <p class="text-muted mb-0">We recommend an image of at least 400X400. GIFs work too.</p>
                        </div>
                    </div>

                    <div class="col-lg-8 col-md-7 col-12">
                        <div class="ms-lg-5">
                            <div class="rounded shadow">
                                <div class="p-4 border-bottom">
                                    <h5 class="mb-0">Edit Profile :</h5>
                                </div>
    
                                <div class="p-4">
                                    <form class="profile-edit">
                                        <div class="row">
                                            <div class="col-12 mb-4">
                                                <label class="form-label h6">Display Name</label>
                                                <input name="name" id="first" type="text" class="form-control" value="streetboyyy">
                                            </div>
        
                                            <div class="col-12 mb-4">
                                                <label class="form-label h6">URL</label>
                                                <div class="form-icon">
                                                    <input name="url" id="Coral-url" type="url" class="form-control" value="https://Coral.exe/streetboyyy">
                                                </div>
                                            </div>
            
                                            <div class="col-12 mb-4">
                                                <label class="form-label h6">Bio</label>
                                                <textarea name="comments" id="comments" rows="3" class="form-control" placeholder="I'm a Digital Artist. Digital Art with over 3 years of experience. Experienced with all stages of the Art cycle for dynamic projects."></textarea>
                                            </div>
        
                                            <div class="col-12 mb-4">
                                                <label class="form-label h6">Twitter Account</label>
                                                <p class="text-muted">Link your twitter account to gain more trust on the Marketplace</p>
                                                <div class="form-icon">
                                                    <input name="url" id="twitter-url" type="url" class="form-control" value="https://twitter.com/streetboyyy">
                                                </div>
                                            </div>
        
                                            <div class="col-12 mb-4">
                                                <label class="form-label h6">Website</label>
                                                <div class="form-icon">
                                                    <input name="url" id="web-url" type="url" class="form-control" value="https://streetboyyy.com/">
                                                </div>
                                            </div>
            
                                            <div class="col-12 mb-4">
                                                <label class="form-label h6">Email</label>
                                                <input name="email" id="email" type="email" class="form-control" value="streetboyyy@example.com">
                                            </div>
                                        </div>
        
                                        
                                        <div class="row">
                                            <div class="col-12">
                                                <button type="submit" id="submit" name="send" class="btn btn-primary rounded">Update Profile</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
    
                            <div class="rounded shadow mt-4">
                                <div class="p-4 border-bottom">
                                    <h5 class="mb-0">Account Notifications :</h5>
                                </div>
    
                                <div class="p-4">
                                    <div class="d-flex justify-content-between pb-4">
                                        <h6 class="mb-0">When someone mentions me</h6>
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" value="" id="noti1">
                                            <label class="form-check-label" for="noti1"></label>
                                        </div>
                                    </div>
                                    <div class="d-flex justify-content-between py-4 border-top">
                                        <h6 class="mb-0">When someone follows me</h6>
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" value="" checked id="noti2">
                                            <label class="form-check-label" for="noti2"></label>
                                        </div>
                                    </div>
                                    <div class="d-flex justify-content-between py-4 border-top">
                                        <h6 class="mb-0">When shares my activity</h6>
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" value="" id="noti3">
                                            <label class="form-check-label" for="noti3"></label>
                                        </div>
                                    </div>
                                    <div class="d-flex justify-content-between py-4 border-top">
                                        <h6 class="mb-0">When someone messages me</h6>
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" value="" id="noti4">
                                            <label class="form-check-label" for="noti4"></label>
                                        </div>
                                    </div>
                                </div>
                            </div>
    
                            <div class="rounded shadow mt-4">
                                <div class="p-4 border-bottom">
                                    <h5 class="mb-0">Marketing Notifications :</h5>
                                </div>
    
                                <div class="p-4">
                                    <div class="d-flex justify-content-between pb-4">
                                        <h6 class="mb-0">There is a sale or promotion</h6>
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" value="" id="noti5">
                                            <label class="form-check-label" for="noti5"></label>
                                        </div>
                                    </div>
                                    <div class="d-flex justify-content-between py-4 border-top">
                                        <h6 class="mb-0">Company news</h6>
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" value="" id="noti6">
                                            <label class="form-check-label" for="noti6"></label>
                                        </div>
                                    </div>
                                    <div class="d-flex justify-content-between py-4 border-top">
                                        <h6 class="mb-0">Weekly jobs</h6>
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" value="" checked id="noti7">
                                            <label class="form-check-label" for="noti7"></label>
                                        </div>
                                    </div>
                                    <div class="d-flex justify-content-between py-4 border-top">
                                        <h6 class="mb-0">Unsubscribe News</h6>
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" value="" checked id="noti8">
                                            <label class="form-check-label" for="noti8"></label>
                                        </div>
                                    </div>
                                </div>
                            </div>
    
                            <div class="rounded shadow mt-4">
                                <div class="p-4 border-bottom">
                                    <h5 class="mb-0 text-danger">Delete Account :</h5>
                                </div>
    
                                <div class="p-4">
                                    <h6 class="mb-0">Do you want to delete the account? Please press below "Delete" button</h6>
                                    <div class="mt-4">
                                        <button class="btn btn-danger">Delete Account</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <FooterOne/>

        <ScrollToTop/>

    </div>
</template>

<script setup>
    import bg from '@/assets/images/hero/pages.jpg'
    import NftNavLight from '@/components/navbar/nft-nav-light.vue';
    import FooterOne from '@/components/footer-one.vue';
    import ScrollToTop from '@/components/scroll-to-top.vue';

    import user from '@/assets/images/team/1.jpg'
    import { ref } from 'vue'
    let image = ref(user)

    const handleChange = (e) =>{
        e.preventDefault();
        image.value = URL.createObjectURL(e.target.files[0])
    }
</script>

// __Coral_v1.2.0/React/Typescript/src/pages/nft/profile-setting.tsx
import { useState } from 'react';
import { Link } from 'react-router-dom'

import bg from '../../assets/images/hero/pages.jpg'
import team from '../../assets/images/team/1.jpg'

import Footer from '../../components/footer';
import ScrollToTop from '../../components/scroll-to-top';

import { FiCamera } from 'react-icons/fi';
import NftNavLight from '../../components/navbar/nft-nav-light';

export default function ProfileSetting() {
    let [file, setFile] = useState(team);

    function handleChange(e:any) {
        setFile(URL.createObjectURL(e.target.files[0]));
    }
  return (
    <>
        <NftNavLight/>

        <section className="bg-half-170 d-table w-100" style={{backgroundImage:`url(${bg})`, backgroundPosition:'center'}}>
            <div className="bg-overlay bg-gradient-overlay"></div>
            <div className="container">
                <div className="row mt-5 justify-content-center">
                    <div className="col-12">
                        <div className="title-heading text-center">
                            <h5 className="heading fw-semibold mb-0 sub-heading text-white title-dark">Profile Setting</h5>
                        </div>
                    </div>
                </div>

                <div className="position-middle-bottom">
                    <nav aria-label="breadcrumb" className="d-block">
                        <ul className="breadcrumb breadcrumb-muted mb-0 p-0">
                            <li className="breadcrumb-item"><Link to="/">Coral</Link></li>
                            <li className="breadcrumb-item"><Link to="/creators">Creators</Link></li>
                            <li className="breadcrumb-item"><Link to="/creator-profile">@StreetBoy</Link></li>
                            <li className="breadcrumb-item active" aria-current="page">Profile Setting</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </section>

        <div className="position-relative">
            <div className="shape overflow-hidden text-white">
                <svg viewBox="0 0 2880 48" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M0 48H1437.5H2880V0H2160C1442.5 52 720 0 720 0H0V48Z" fill="currentColor"></path>
                </svg>
            </div>
        </div>   

        <section className="section">
            <div className="container">
                <div className="row">
                    <div className="col-lg-9">
                        <h5>You can set preferred display name, create your branded profile URL and manage other personal settings.</h5>
                    </div>
                </div>
                <div className="row g-4">
                    <div className="col-lg-4 col-md-5 col-12">
                        <div className="profile-pic">
                            <input id="pro-img" name="profile-image" type="file" className="d-none" onChange={(e) =>handleChange(e)}/>
                            <div className="position-relative d-inline-block">
                                <img src={file} className="avatar avatar-medium img-thumbnail rounded-pill shadow-sm" id="profile-image" alt=""/>
                                <label className="icons position-absolute bottom-0 end-0" htmlFor="pro-img"><span className="btn btn-icon btn-sm btn-pills btn-primary"><FiCamera className="icons"/></span></label>
                            </div>
                        </div>

                        <div className="mt-4">
                            <p className="text-muted mb-0">We recommend an image of at least 400X400. GIFs work too.</p>
                        </div>
                    </div>

                    <div className="col-lg-8 col-md-7 col-12">
                        <div className="ms-lg-5">
                            <div className="rounded shadow">
                                <div className="p-4 border-bottom">
                                    <h5 className="mb-0">Edit Profile :</h5>
                                </div>
    
                                <div className="p-4">
                                    <form className="profile-edit">
                                        <div className="row">
                                            <div className="col-12 mb-4">
                                                <label className="form-label h6">Display Name</label>
                                                <input name="name" id="first" type="text" className="form-control" value="streetboyyy"/>
                                            </div>
        
                                            <div className="col-12 mb-4">
                                                <label className="form-label h6">URL</label>
                                                <div className="form-icon">
                                                    <input name="url" id="Coral-url" type="url" className="form-control" value="https://Coral.exe/streetboyyy"/>
                                                </div>
                                            </div>
            
                                            <div className="col-12 mb-4">
                                                <label className="form-label h6">Bio</label>
                                                <textarea name="comments" id="comments" rows={3} className="form-control" placeholder="I'm a Digital Artist. Digital Art with over 3 years of experience. Experienced with all stages of the Art cycle for dynamic projects."></textarea>
                                            </div>
        
                                            <div className="col-12 mb-4">
                                                <label className="form-label h6">Twitter Account</label>
                                                <p className="text-muted">Link your twitter account to gain more trust on the Marketplace</p>
                                                <div className="form-icon">
                                                    <input name="url" id="twitter-url" type="url" className="form-control" placeholder='https://twitter.com/streetboyyy'/>
                                                </div>
                                            </div>
        
                                            <div className="col-12 mb-4">
                                                <label className="form-label h6">Website</label>
                                                <div className="form-icon">
                                                    <input name="url" id="web-url" type="url" className="form-control" value="https://streetboyyy.com/"/>
                                                </div>
                                            </div>
            
                                            <div className="col-12 mb-4">
                                                <label className="form-label h6">Email</label>
                                                <input name="email" id="email" type="email" className="form-control" value="streetboyyy@example.com"/>
                                            </div>
                                        </div>
        
                                        
                                        <div className="row">
                                            <div className="col-12">
                                                <button type="submit" id="submit" name="send" className="btn btn-primary rounded">Update Profile</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
    
                            <div className="rounded shadow mt-4">
                                <div className="p-4 border-bottom">
                                    <h5 className="mb-0">Account Notifications :</h5>
                                </div>
    
                                <div className="p-4">
                                    <div className="d-flex justify-content-between pb-4">
                                        <h6 className="mb-0">When someone mentions me</h6>
                                        <div className="form-check">
                                            <input className="form-check-input" type="checkbox" value="" id="noti1"/>
                                            <label className="form-check-label" htmlFor="noti1"></label>
                                        </div>
                                    </div>
                                    <div className="d-flex justify-content-between py-4 border-top">
                                        <h6 className="mb-0">When someone follows me</h6>
                                        <div className="form-check">
                                            <input className="form-check-input" type="checkbox" value="" checked id="noti2"/>
                                            <label className="form-check-label" htmlFor="noti2"></label>
                                        </div>
                                    </div>
                                    <div className="d-flex justify-content-between py-4 border-top">
                                        <h6 className="mb-0">When shares my activity</h6>
                                        <div className="form-check">
                                            <input className="form-check-input" type="checkbox" value="" id="noti3"/>
                                            <label className="form-check-label" htmlFor="noti3"></label>
                                        </div>
                                    </div>
                                    <div className="d-flex justify-content-between py-4 border-top">
                                        <h6 className="mb-0">When someone messages me</h6>
                                        <div className="form-check">
                                            <input className="form-check-input" type="checkbox" value="" id="noti4"/>
                                            <label className="form-check-label" htmlFor="noti4"></label>
                                        </div>
                                    </div>
                                </div>
                            </div>
    
                            <div className="rounded shadow mt-4">
                                <div className="p-4 border-bottom">
                                    <h5 className="mb-0">Marketing Notifications :</h5>
                                </div>
    
                                <div className="p-4">
                                    <div className="d-flex justify-content-between pb-4">
                                        <h6 className="mb-0">There is a sale or promotion</h6>
                                        <div className="form-check">
                                            <input className="form-check-input" type="checkbox" value="" id="noti5"/>
                                            <label className="form-check-label" htmlFor="noti5"></label>
                                        </div>
                                    </div>
                                    <div className="d-flex justify-content-between py-4 border-top">
                                        <h6 className="mb-0">Company news</h6>
                                        <div className="form-check">
                                            <input className="form-check-input" type="checkbox" value="" id="noti6"/>
                                            <label className="form-check-label" htmlFor="noti6"></label>
                                        </div>
                                    </div>
                                    <div className="d-flex justify-content-between py-4 border-top">
                                        <h6 className="mb-0">Weekly jobs</h6>
                                        <div className="form-check">
                                            <input className="form-check-input" type="checkbox" value="" checked id="noti7"/>
                                            <label className="form-check-label" htmlFor="noti7"></label>
                                        </div>
                                    </div>
                                    <div className="d-flex justify-content-between py-4 border-top">
                                        <h6 className="mb-0">Unsubscribe News</h6>
                                        <div className="form-check">
                                            <input className="form-check-input" type="checkbox" value="" checked id="noti8"/>
                                            <label className="form-check-label" htmlFor="noti8"></label>
                                        </div>
                                    </div>
                                </div>
                            </div>
    
                            <div className="rounded shadow mt-4">
                                <div className="p-4 border-bottom">
                                    <h5 className="mb-0 text-danger">Delete Account :</h5>
                                </div>
    
                                <div className="p-4">
                                    <h6 className="mb-0">Do you want to delete the account? Please press below "Delete" button</h6>
                                    <div className="mt-4">
                                        <button className="btn btn-danger">Delete Account</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <Footer/>

        <ScrollToTop/>
    </>
  )
}
