// __Coral_v1.2.0/React/Javascript/src/App.jsx
import { Route, Routes } from 'react-router-dom'
import IndexBusiness from './pages/index/index-business'
import IndexSaas from './pages/index/index-saas'
import IndexConsulting from './pages/index/index-consulting'
import IndexCryptocurrency from './pages/index/index-cryptocurrency'
import IndexDigitalMarketing from './pages/index/index-digital-marketing'
import IndexFinance from './pages/index/index-finance'
import IndexTtSolution from './pages/index/index-it-solution'
import IndexHospital from './pages/index/index-hospital'
import IndexNft from './pages/index/index-nft'
import IndexMinimalPortfolio from './pages/index/index-minimal-portfolio'
import IndexWebHosting from './pages/index/index-web-hosting'
import IndexYoga from './pages/index/index-yoga'
import IndexCharity from './pages/index/index-charity'
import AboutUs from './pages/inner-pages/aboutus'
import Services from './pages/inner-pages/services'
import ServiceDetail from './pages/inner-pages/service-detail'
import Pricing from './pages/inner-pages/pricing'
import Team from './pages/inner-pages/team'
import Testimonial from './pages/inner-pages/testimonial'
import Faqs from './pages/inner-pages/faqs'
import NftExplore from './pages/nft/nft-explore'
import NftDetail from './pages/nft/nft-detail'
import Collection from './pages/nft/collection'
import Wallet from './pages/nft/wallet'
import UploadItem from './pages/nft/upload-item'
import Creators from './pages/nft/creators'
import CreatorProfile from './pages/nft/creator-profile'
import ProfileSetting from './pages/nft/profile-setting'
import Login from './pages/auth/login'
import Signup from './pages/auth/signup'
import ResetPassword from './pages/auth/reset-password'
import LockScreen from './pages/auth/lock-screen'
import Terms from './pages/utility/terms'
import Privacy from './pages/utility/privacy'
import Comingsoon from './pages/special/comingsoon'
import Maintenance from './pages/special/maintenance'
import Error from './pages/special/error'
import PortfolioModernTwo from './pages/portfolio/modern/portfolio-modern-two'
import PortfolioModernThree from './pages/portfolio/modern/portfolio-modern-three'
import PortfolioModernFour from './pages/portfolio/modern/portfolio-modern-four'
import PortfolioModernFive from './pages/portfolio/modern/portfolio-modern-five'
import PortfolioModernSix from './pages/portfolio/modern/portfolio-modern-six'
import PortfolioClassicTwo from './pages/portfolio/classic/portfolio-classic-two'
import PortfolioClassicThree from './pages/portfolio/classic/portfolio-classic-three'
import PortfolioClassicFour from './pages/portfolio/classic/portfolio-classic-four'
import PortfolioClassicFive from './pages/portfolio/classic/portfolio-classic-five'
import PortfolioClassicSix from './pages/portfolio/classic/portfolio-classic-six'
import PortfolioCreativeTwo from './pages/portfolio/creative/portfolio-creative-two'
import PortfolioCreativeThree from './pages/portfolio/creative/portfolio-creative-three'
import PortfolioCreativeFour from './pages/portfolio/creative/portfolio-creative-four'
import PortfolioCreativeFive from './pages/portfolio/creative/portfolio-creative-five'
import PortfolioCreativeSix from './pages/portfolio/creative/portfolio-creative-six'
import PortfolioMasonryTwo from './pages/portfolio/masonry/portfolio-masonry-two'
import PortfolioMasonryThree from './pages/portfolio/masonry/portfolio-masonry-three'
import PortfolioMasonryFour from './pages/portfolio/masonry/portfolio-masonry-four'
import PortfolioMasonryFive from './pages/portfolio/masonry/portfolio-masonry-five'
import PortfolioMasonrySix from './pages/portfolio/masonry/portfolio-masonry-six'
import PortfolioDetail from './pages/portfolio/portfolio-detail'
import PortfolioDetailTwo from './pages/portfolio/portfolio-detail-two'
import Blogs from './pages/blog/blogs'
import BlogSidebar from './pages/blog/blog-sidebar'
import BlogStandardPost from './pages/blog/blog-standard-post'
import BlogGalleryPost from './pages/blog/blog-gallery-post'
import BlogSliderPost from './pages/blog/blog-slider-post'
import BlogLinkPost from './pages/blog/blog-link-post'
import BlogStoryPost from './pages/blog/blog-story-post'
import BlogYoutubePost from './pages/blog/blog-youtube-post'
import BlogHtmlVideoPost from './pages/blog/blog-html-video-post'
import BlogAudioPost from './pages/blog/blog-audio-post'
import BlogHtmlAudio from './pages/blog/blog-html-audio'
import BlogBlockquotePost from './pages/blog/blog-blockquote-post'
import BlogVimeoPost from './pages/blog/blog-vimeo-post'
import BlogLeftSidebarPost from './pages/blog/blog-left-sidebar-post'
import Contactus from './pages/inner-pages/contactus'

function App() {

  return (
    <>
      <Routes>
        <Route path='/' element={<IndexBusiness/>}/>
        <Route path='/index-saas' element={<IndexSaas/>}/>
        <Route path='/index-consulting' element={<IndexConsulting/>}/>
        <Route path='/index-cryptocurrency' element={<IndexCryptocurrency/>}/>
        <Route path='/index-digital-marketing' element={<IndexDigitalMarketing/>}/>
        <Route path='/index-finance' element={<IndexFinance/>}/>
        <Route path='/index-it-solution' element={<IndexTtSolution/>}/>
        <Route path='/index-hospital' element={<IndexHospital/>}/>
        <Route path='/index-nft' element={<IndexNft/>}/>
        <Route path='/index-minimal-portfolio' element={<IndexMinimalPortfolio/>}/>
        <Route path='/index-web-hosting' element={<IndexWebHosting/>}/>
        <Route path='/index-yoga' element={<IndexYoga/>}/>
        <Route path='/index-charity' element={<IndexCharity/>}/>

        <Route path='/aboutus' element={<AboutUs/>}/>
        <Route path='/services' element={<Services/>}/>
        <Route path='/service-detail' element={<ServiceDetail/>}/>
        <Route path='/pricing' element={<Pricing/>}/>
        <Route path='/team' element={<Team/>}/>
        <Route path='/testimonial' element={<Testimonial/>}/>
        <Route path='/faqs' element={<Faqs/>}/>

        <Route path='/nft-explore' element={<NftExplore/>}/>
        <Route path='/nft-detail' element={<NftDetail/>}/>
        <Route path='/nft-detail/:id' element={<NftDetail/>}/>
        <Route path='/collection' element={<Collection/>}/>
        <Route path='/wallet' element={<Wallet/>}/>
        <Route path='/upload-item' element={<UploadItem/>}/>
        <Route path='/creators' element={<Creators/>}/>
        <Route path='/creator-profile' element={<CreatorProfile/>}/>
        <Route path='/profile-setting' element={<ProfileSetting/>}/>

        <Route path='/login' element={<Login/>}/>
        <Route path='/signup' element={<Signup/>}/>
        <Route path='/reset-password' element={<ResetPassword/>}/>
        <Route path='/lock-screen' element={<LockScreen/>}/>

        <Route path='/terms' element={<Terms/>}/>
        <Route path='/privacy' element={<Privacy/>}/>

        <Route path='/comingsoon' element={<Comingsoon/>}/>
        <Route path='/maintenance' element={<Maintenance/>}/>
        <Route path='/error' element={<Error/>}/>

        <Route path='/portfolio-modern-two' element={<PortfolioModernTwo/>}/>
        <Route path='/portfolio-modern-three' element={<PortfolioModernThree/>}/>
        <Route path='/portfolio-modern-four' element={<PortfolioModernFour/>}/>
        <Route path='/portfolio-modern-five' element={<PortfolioModernFive/>}/>
        <Route path='/portfolio-modern-six' element={<PortfolioModernSix/>}/>

        <Route path='/portfolio-classic-two' element={<PortfolioClassicTwo/>}/>
        <Route path='/portfolio-classic-three' element={<PortfolioClassicThree/>}/>
        <Route path='/portfolio-classic-four' element={<PortfolioClassicFour/>}/>
        <Route path='/portfolio-classic-five' element={<PortfolioClassicFive/>}/>
        <Route path='/portfolio-classic-six' element={<PortfolioClassicSix/>}/>

        <Route path='/portfolio-creative-two' element={<PortfolioCreativeTwo/>}/>
        <Route path='/portfolio-creative-three' element={<PortfolioCreativeThree/>}/>
        <Route path='/portfolio-creative-four' element={<PortfolioCreativeFour/>}/>
        <Route path='/portfolio-creative-five' element={<PortfolioCreativeFive/>}/>
        <Route path='/portfolio-creative-six' element={<PortfolioCreativeSix/>}/>

        <Route path='/portfolio-masonry-two' element={<PortfolioMasonryTwo/>}/>
        <Route path='/portfolio-masonry-three' element={<PortfolioMasonryThree/>}/>
        <Route path='/portfolio-masonry-four' element={<PortfolioMasonryFour/>}/>
        <Route path='/portfolio-masonry-five' element={<PortfolioMasonryFive/>}/>
        <Route path='/portfolio-masonry-six' element={<PortfolioMasonrySix/>}/>

        <Route path='/portfolio-detail' element={<PortfolioDetail/>}/>
        <Route path='/portfolio-detail-two' element={<PortfolioDetailTwo/>}/>

        <Route path='/blogs' element={<Blogs/>}/>
        <Route path='/blog-sidebar' element={<BlogSidebar/>}/>
        <Route path='/blog-standard-post' element={<BlogStandardPost/>}/>
        <Route path='/blog-standard-post/:id' element={<BlogStandardPost/>}/>
        <Route path='/blog-gallery-post' element={<BlogGalleryPost/>}/>
        <Route path='/blog-slider-post' element={<BlogSliderPost/>}/>
        <Route path='/blog-link-post' element={<BlogLinkPost/>}/>
        <Route path='/blog-story-post' element={<BlogStoryPost/>}/>
        <Route path='/blog-youtube-post' element={<BlogYoutubePost/>}/>
        <Route path='/blog-html-video-post' element={<BlogHtmlVideoPost/>}/>
        <Route path='/blog-audio-post' element={<BlogAudioPost/>}/>
        <Route path='/blog-html-audio' element={<BlogHtmlAudio/>}/>
        <Route path='/blog-blockquote-post' element={<BlogBlockquotePost/>}/>
        <Route path='/blog-vimeo-post' element={<BlogVimeoPost/>}/>
        <Route path='/blog-left-sidebar-post' element={<BlogLeftSidebarPost/>}/>

        <Route path='/contactus' element={<Contactus/>}/>
      </Routes>
    </>
  )
}

export default App

// __Coral_v1.2.0/Svelte/src/App.svelte
<script>
// @ts-nocheck

    import { Router, Route, useLocation  } from "svelte-routing";
    import IndexBusiness from "./pages/index/index-business.svelte";

    import { onMount, tick } from 'svelte';
    import Tobii from 'tobii';
    import '../node_modules/tobii/dist/css/tobii.min.css';
    import ScrollToTop from "./components/scroll-to-top.svelte";
    import IndexSaas from "./pages/index/index-saas.svelte";
    import IndexConsulting from "./pages/index/index-consulting.svelte";
    import IndexCryptocurrency from "./pages/index/index-cryptocurrency.svelte";
    import IndexDigitalMarketing from "./pages/index/index-digital-marketing.svelte";
    import IndexFinance from "./pages/index/index-finance.svelte";
    import IndexItSolution from "./pages/index/index-it-solution.svelte";
    import IndexHospital from "./pages/index/index-hospital.svelte";
    import IndexNft from "./pages/index/index-nft.svelte";
    import IndexMinimalPortfolio from "./pages/index/index-minimal-portfolio.svelte";
    import IndexWebHosting from "./pages/index/index-web-hosting.svelte";
    import IndexYoga from "./pages/index/index-yoga.svelte";
    import IndexCharity from "./pages/index/index-charity.svelte";
    import Aboutus from "./pages/inner-pages/aboutus.svelte";
    import Services from "./pages/inner-pages/services.svelte";
    import ServiceDetail from "./pages/inner-pages/service-detail.svelte";
    import Pricing from "./pages/inner-pages/pricing.svelte";
    import Team from "./pages/inner-pages/team.svelte";
    import Testimonial from "./pages/inner-pages/testimonial.svelte";
    import Faqs from "./pages/inner-pages/faqs.svelte";
    import NftExplore from "./pages/nft/nft-explore.svelte";
    import NftDetail from "./pages/nft/nft-detail.svelte";
    import Collection from "./pages/nft/collection.svelte";
    import Wallet from "./pages/nft/wallet.svelte";
    import UploadItem from "./pages/nft/upload-item.svelte";
    import Creators from "./pages/nft/creators.svelte";
    import CreatorProfile from "./pages/nft/creator-profile.svelte";
    import ProfileSetting from "./pages/nft/profile-setting.svelte";
    import Login from "./pages/auth/login.svelte";
    import Signup from "./pages/auth/signup.svelte";
    import ResetPassword from "./pages/auth/reset-password.svelte";
    import LockScreen from "./pages/auth/lock-screen.svelte";
    import Terms from "./pages/utility/terms.svelte";
    import Privacy from "./pages/utility/privacy.svelte";
    import Comingsoon from "./pages/special/comingsoon.svelte";
    import Maintenance from "./pages/special/maintenance.svelte";
    import Error from "./pages/special/error.svelte";
    import PortfolioModernTwo from "./pages/portfolio/modern/portfolio-modern-two.svelte";
    import PortfolioModernThree from "./pages/portfolio/modern/portfolio-modern-three.svelte";
    import PortfolioModernFour from "./pages/portfolio/modern/portfolio-modern-four.svelte";
    import PortfolioModernFive from "./pages/portfolio/modern/portfolio-modern-five.svelte";
    import PortfolioModernSix from "./pages/portfolio/modern/portfolio-modern-six.svelte";
    import PortfolioClassicTwo from "./pages/portfolio/classic/portfolio-classic-two.svelte";
    import PortfolioClassicThree from "./pages/portfolio/classic/portfolio-classic-three.svelte";
    import PortfolioClassicFour from "./pages/portfolio/classic/portfolio-classic-four.svelte";
    import PortfolioClassicFive from "./pages/portfolio/classic/portfolio-classic-five.svelte";
    import PortfolioClassicSix from "./pages/portfolio/classic/portfolio-classic-six.svelte";
    import PortfolioCreativeTwo from "./pages/portfolio/creative/portfolio-creative-two.svelte";
    import PortfolioCreativeThree from "./pages/portfolio/creative/portfolio-creative-three.svelte";
    import PortfolioCreativeFour from "./pages/portfolio/creative/portfolio-creative-four.svelte";
    import PortfolioCreativeFive from "./pages/portfolio/creative/portfolio-creative-five.svelte";
    import PortfolioCreativeSix from "./pages/portfolio/creative/portfolio-creative-six.svelte";
    import PortfolioMasonryTwo from "./pages/portfolio/masonry/portfolio-masonry-two.svelte";
    import PortfolioMasonryThree from "./pages/portfolio/masonry/portfolio-masonry-three.svelte";
    import PortfolioMasonryFour from "./pages/portfolio/masonry/portfolio-masonry-four.svelte";
    import PortfolioMasonryFive from "./pages/portfolio/masonry/portfolio-masonry-five.svelte";
    import PortfolioMasonrySix from "./pages/portfolio/masonry/portfolio-masonry-six.svelte";
    import PortfolioDetail from "./pages/portfolio/portfolio-detail.svelte";
    import PortfolioDetailTwo from "./pages/portfolio/portfolio-detail-two.svelte";
    import Blogs from "./pages/blog/blogs.svelte";
    import BlogSidebar from "./pages/blog/blog-sidebar.svelte";
    import BlogStandardPost from "./pages/blog/blog-standard-post.svelte";
    import BlogGalleryPost from "./pages/blog/blog-gallery-post.svelte";
    import BlogSliderPost from "./pages/blog/blog-slider-post.svelte";
    import BlogLinkPost from "./pages/blog/blog-link-post.svelte";
    import BlogStoryPost from "./pages/blog/blog-story-post.svelte";
    import BlogYoutubePost from "./pages/blog/blog-youtube-post.svelte";
    import BlogHtmlVideoPost from "./pages/blog/blog-html-video-post.svelte";
    import BlogAudioPost from "./pages/blog/blog-audio-post.svelte";
    import BlogHtmlAudio from "./pages/blog/blog-html-audio.svelte";
    import BlogBlockquotePost from "./pages/blog/blog-blockquote-post.svelte";
    import BlogVimeoPost from "./pages/blog/blog-vimeo-post.svelte";
    import BlogLeftSidebarPost from "./pages/blog/blog-left-sidebar-post.svelte";
    import Contactus from "./pages/inner-pages/contactus.svelte";

    let tobii;

    onMount(() => {
        tobii = new Tobii();
    });

</script>

<main>
    <Router>
        <Route path="/"><IndexBusiness/></Route>
        <Route path="/index-saas"><IndexSaas/></Route>
        <Route path="/index-consulting"><IndexConsulting/></Route>
        <Route path="/index-cryptocurrency"><IndexCryptocurrency/></Route>
        <Route path="/index-digital-marketing"><IndexDigitalMarketing/></Route>
        <Route path="/index-finance"><IndexFinance/></Route>
        <Route path="/index-it-solution"><IndexItSolution/></Route>
        <Route path="/index-hospital"><IndexHospital/></Route>
        <Route path="/index-nft"><IndexNft/></Route>
        <Route path="/index-minimal-portfolio"><IndexMinimalPortfolio/></Route>
        <Route path="/index-web-hosting"><IndexWebHosting/></Route>
        <Route path="/index-yoga"><IndexYoga/></Route>
        <Route path="/index-charity"><IndexCharity/></Route>
        <Route path="/aboutus"><Aboutus/></Route>
        <Route path="/services"><Services/></Route>
        <Route path="/service-detail"><ServiceDetail/></Route>
        <Route path="/pricing"><Pricing/></Route>
        <Route path="/team"><Team/></Route>
        <Route path="/testimonial"><Testimonial/></Route>
        <Route path="/faqs"><Faqs/></Route>
        <Route path="/nft-explore"><NftExplore/></Route>
        <Route path="/nft-detail"><NftDetail/></Route>
        <Route path="/nft-detail/:id" let:params><NftDetail id={params.id}/></Route>
        <Route path="/collection"><Collection/></Route>
        <Route path="/wallet"><Wallet/></Route>
        <Route path="/upload-item"><UploadItem/></Route>
        <Route path="/creators"><Creators/></Route>
        <Route path="/creator-profile"><CreatorProfile/></Route>
        <Route path="/profile-setting"><ProfileSetting/></Route>
        <Route path="/login"><Login/></Route>
        <Route path="/signup"><Signup/></Route>
        <Route path="/reset-password"><ResetPassword/></Route>
        <Route path="/lock-screen"><LockScreen/></Route>
        <Route path="/terms"><Terms/></Route>
        <Route path="/privacy"><Privacy/></Route>
        <Route path="/comingsoon"><Comingsoon/></Route>
        <Route path="/maintenance"><Maintenance/></Route>
        <Route path="/error"><Error/></Route>
        <Route path="/portfolio-modern-two"><PortfolioModernTwo/></Route>
        <Route path="/portfolio-modern-three"><PortfolioModernThree/></Route>
        <Route path="/portfolio-modern-four"><PortfolioModernFour/></Route>
        <Route path="/portfolio-modern-five"><PortfolioModernFive/></Route>
        <Route path="/portfolio-modern-six"><PortfolioModernSix/></Route>
        <Route path="/portfolio-classic-two"><PortfolioClassicTwo/></Route>
        <Route path="/portfolio-classic-three"><PortfolioClassicThree/></Route>
        <Route path="/portfolio-classic-four"><PortfolioClassicFour/></Route>
        <Route path="/portfolio-classic-five"><PortfolioClassicFive/></Route>
        <Route path="/portfolio-classic-six"><PortfolioClassicSix/></Route>
        <Route path="/portfolio-creative-two"><PortfolioCreativeTwo/></Route>
        <Route path="/portfolio-creative-three"><PortfolioCreativeThree/></Route>
        <Route path="/portfolio-creative-four"><PortfolioCreativeFour/></Route>
        <Route path="/portfolio-creative-five"><PortfolioCreativeFive/></Route>
        <Route path="/portfolio-creative-six"><PortfolioCreativeSix/></Route>
        <Route path="/portfolio-masonry-two"><PortfolioMasonryTwo/></Route>
        <Route path="/portfolio-masonry-three"><PortfolioMasonryThree/></Route>
        <Route path="/portfolio-masonry-four"><PortfolioMasonryFour/></Route>
        <Route path="/portfolio-masonry-five"><PortfolioMasonryFive/></Route>
        <Route path="/portfolio-masonry-six"><PortfolioMasonrySix/></Route>
        <Route path="/portfolio-detail"><PortfolioDetail/></Route>
        <Route path="/portfolio-detail-two"><PortfolioDetailTwo/></Route>
        <Route path="/blogs"><Blogs/></Route>
        <Route path="/blog-sidebar"><BlogSidebar/></Route>
        <Route path="/blog-standard-post"><BlogStandardPost/></Route>
        <Route path="/blog-standard-post/:id" let:params><BlogStandardPost id={params.id}/></Route>
        <Route path="/blog-gallery-post"><BlogGalleryPost/></Route>
        <Route path="/blog-slider-post"><BlogSliderPost/></Route>
        <Route path="/blog-link-post"><BlogLinkPost/></Route>
        <Route path="/blog-story-post"><BlogStoryPost/></Route>
        <Route path="/blog-youtube-post"><BlogYoutubePost/></Route>
        <Route path="/blog-html-video-post"><BlogHtmlVideoPost/></Route>
        <Route path="/blog-audio-post"><BlogAudioPost/></Route>
        <Route path="/blog-html-audio"><BlogHtmlAudio/></Route>
        <Route path="/blog-blockquote-post"><BlogBlockquotePost/></Route>
        <Route path="/blog-vimeo-post"><BlogVimeoPost/></Route>
        <Route path="/blog-left-sidebar-post"><BlogLeftSidebarPost/></Route>
        <Route path="/contactus"><Contactus/></Route>
    </Router>
    
    <ScrollToTop/>

</main>
