// src/components/services/hosting-services.vue
<template>
    <div class="row justify-content-center">
        <div class="col-lg-12">
            <div class="features-absolute">
                <div class="row row-cols-lg-5 row-cols-md-3 row-cols-lg-2 row-cols-lg-1 g-4">
                    <div v-for="(item, index) in data" :key="index" class="col">
                        <div class="features rounded shadow p-4 bg-primary bg-gradient">
                            <img :src="item.image" class="avatar avatar-md-sm" alt="">

                            <div class="mt-3">
                                <router-link to="#" class="text-white fw-semibold">{{item.title}}</router-link>
                                <small class="text-white-50 d-block mt-1">{{item.value}}</small>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script setup>
    import { ref } from 'vue'
    import hosting1 from '@/assets/images/hosting/1.png'
    import hosting2 from '@/assets/images/hosting/2.png'
    import hosting3 from '@/assets/images/hosting/3.png'
    import hosting4 from '@/assets/images/hosting/4.png'
    import hosting5 from '@/assets/images/hosting/5.png'

    let data = ref([
        {
            image:hosting1,
            title:'Shared Hosting',
            value:'Starting $2.99/month'
        },
        {
            image:hosting2,
            title:'VPS Hosting',
            value:'Starting $2.99/month'
        },
        {
            image:hosting3,
            title:'Dedicated Server',
            value:'Starting $2.99/month'
        },
        {
            image:hosting4,
            title:'Cloud Hosting',
            value:'Starting $2.99/month'
        },
        {
            image:hosting5,
            title:'Reseller Hosting',
            value:'Starting $2.99/month'
        },
    ])

</script>

// __Coral_v1.2.0/React/Javascript/src/components/services/hosting-services.jsx
import { Link } from 'react-router-dom'

import image1 from '../../assets/images/hosting/1.png'
import image2 from '../../assets/images/hosting/2.png'
import image3 from '../../assets/images/hosting/3.png'
import image4 from '../../assets/images/hosting/4.png'
import image5 from '../../assets/images/hosting/5.png'

let data = [
    {
        image:image1,
        title:'Shared Hosting',
        value:'Starting $2.99/month'
    },
    {
        image:image2,
        title:'VPS Hosting',
        value:'Starting $2.99/month'
    },
    {
        image:image3,
        title:'Dedicated Server',
        value:'Starting $2.99/month'
    },
    {
        image:image4,
        title:'Cloud Hosting',
        value:'Starting $2.99/month'
    },
    {
        image:image5,
        title:'Reseller Hosting',
        value:'Starting $2.99/month'
    },
]

export default function HostingServices() {
  return (
    <div className="row justify-content-center">
        <div className="col-lg-12">
            <div className="features-absolute">
                <div className="row row-cols-lg-5 row-cols-md-3 row-cols-lg-2 row-cols-lg-1 g-4">
                    {data.map((item,index)=>( 
                        <div className="col" key={index}>
                            <div className="features rounded shadow p-4 bg-primary bg-gradient">
                                <img src={item.image} className="avatar avatar-md-sm" alt=""/>

                                <div className="mt-3">
                                    <Link to="" className="text-white fw-semibold">{item.title}</Link>
                                    <small className="text-white-50 d-block mt-1">{item.value}</small>
                                </div>
                            </div>
                        </div>
                    ))}
                </div>
            </div>
        </div>
    </div>
  )
}
