// src/components/services/services-two.vue
<template>
    <div class="row align-items-center g-4">
        <div v-for="(item, index) in servicesData.slice(0,3)" :key="index" class="col-lg-4 col-md-6 col-12">
            <div class="position-relative features text-center rounded shadow p-4 pt-5">
                <div class="position-relative d-flex justify-content-center">
                    <i :data-feather="item.icon" class="fea icon-md text-primary z-1"></i>
                    <div class="feature-icon bg-soft-primary position-absolute top-0 translate-middle"></div>
                </div>

                <div class="mt-4">
                    <router-link to="/service-detail" class="h5 text-dark link-title">{{item.title}}</router-link>
                    <p class="text-muted mt-3">{{item.desc}}</p>
                    <router-link to="/service-detail" class="text-primary">Learn More <i class="mdi mdi-arrow-right align-middle"></i></router-link>
                </div>
            </div>
        </div>
    </div>
</template>

<script setup>
    import { servicesData } from '@/data/data';
</script>

// __Coral_v1.2.0/React/Javascript/src/components/services/services-two.jsx
import { servicesData } from '../../data/data'
import { Link } from 'react-router-dom'

export default function ServicesTwo() {
  return (
    <div className="row g-4">
        {servicesData.map((item,index)=>{
            let Icon = item.icon
            return(
                <div className="col-lg-4 col-md-6 col-12" key={index}>
                    <div className="position-relative features text-center rounded p-4 pt-5">
                        <div className="position-relative d-flex justify-content-center">
                            <Icon className="fea icon-md text-primary z-1"></Icon>
                            <div className="feature-icon bg-soft-primary position-absolute top-0 translate-middle"></div>
                        </div>

                        <div className="mt-4">
                            <Link to="/service-detail" className="h5 text-dark link-title">{item.title}</Link>
                            <p className="text-muted mt-3">{item.desc}</p>
                            <Link to="/service-detail" className="text-primary">Learn More <i className="mdi mdi-arrow-right align-middle"></i></Link>
                        </div>
                    </div>
                </div>
            )
        })}
    </div>
  )
}
