// __Coral_v1.2.0/Svelte/src/pages/nft/profile-setting.svelte
<script>
    import NftNavlight from "../../components/navbar/nft-navlight.svelte";
    import bg from '../../assets/images/hero/pages.jpg'
    import team from '../../assets/images/team/1.jpg'
    import { Link } from "svelte-routing";
    import Footer from "../../components/footer.svelte";

    let file = ""

  function handleChange(event) {
    file = URL.createObjectURL(event.target.files[0])
  }

</script>

<NftNavlight/>

<section class="bg-half-170 d-table w-100" style="background: url({bg}) center;">
    <div class="bg-overlay bg-gradient-overlay"></div>
    <div class="container">
        <div class="row mt-5 justify-content-center">
            <div class="col-12">
                <div class="title-heading text-center">
                    <h5 class="heading fw-semibold mb-0 sub-heading text-white title-dark">Profile Setting</h5>
                </div>
            </div>
        </div>

        <div class="position-middle-bottom">
            <nav aria-label="breadcrumb" class="d-block">
                <ul class="breadcrumb breadcrumb-muted mb-0 p-0">
                    <li class="breadcrumb-item"><Link to="/">Coral</Link></li>
                    <li class="breadcrumb-item"><Link to="/creators">Creators</Link></li>
                    <li class="breadcrumb-item"><Link to="/creator-profile">@StreetBoy</Link></li>
                    <li class="breadcrumb-item active" aria-current="page">Profile Setting</li>
                </ul>
            </nav>
        </div>
    </div>
</section>

<div class="position-relative">
    <div class="shape overflow-hidden text-white">
        <svg viewBox="0 0 2880 48" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M0 48H1437.5H2880V0H2160C1442.5 52 720 0 720 0H0V48Z" fill="currentColor"></path>
        </svg>
    </div>
</div>

<section class="section">
    <div class="container">
        <div class="row">
            <div class="col-lg-9">
                <h5>You can set preferred display name, create your branded profile URL and manage other personal settings.</h5>
            </div>
        </div>
        <div class="row g-4">
            <div class="col-lg-4 col-md-5 col-12">
                <div class="profile-pic">
                    <input id="pro-img" name="profile-image" type="file" class="d-none" on:change={handleChange} />
                    <div class="position-relative d-inline-block">
                        {#if file}
                             <img src={file} class="avatar avatar-medium img-thumbnail rounded-pill shadow-sm" id="profile-image" alt="">
                        {:else}
                             <img src={team} class="avatar avatar-medium img-thumbnail rounded-pill shadow-sm" id="profile-image" alt="">
                        {/if}
                        <label class="icons position-absolute bottom-0 end-0" for="pro-img"><span class="btn btn-icon btn-sm btn-pills btn-primary"><i data-feather="camera" class="icons"></i></span></label>
                    </div>
                </div>

                <div class="mt-4">
                    <p class="text-muted mb-0">We recommend an image of at least 400X400. GIFs work too.</p>
                </div>
            </div>

            <div class="col-lg-8 col-md-7 col-12">
                <div class="ms-lg-5">
                    <div class="rounded shadow">
                        <div class="p-4 border-bottom">
                            <h5 class="mb-0">Edit Profile :</h5>
                        </div>

                        <div class="p-4">
                            <form class="profile-edit">
                                <div class="row">
                                    <div class="col-12 mb-4">
                                        <label class="form-label h6" for="name">Display Name</label>
                                        <input name="name" id="first" type="text" class="form-control" value="streetboyyy">
                                    </div>

                                    <div class="col-12 mb-4">
                                        <label class="form-label h6" for="url">URL</label>
                                        <div class="form-icon">
                                            <input name="url" id="Coral-url" type="url" class="form-control" value="https://Coral.exe/streetboyyy">
                                        </div>
                                    </div>
    
                                    <div class="col-12 mb-4">
                                        <label class="form-label h6" for="comments">Bio</label>
                                        <textarea name="comments" id="comments" rows="3" class="form-control" placeholder="I'm a Digital Artist. Digital Art with over 3 years of experience. Experienced with all stages of the Art cycle for dynamic projects."></textarea>
                                    </div>

                                    <div class="col-12 mb-4">
                                        <label class="form-label h6" for="account">Twitter Account</label>
                                        <p class="text-muted">Link your twitter account to gain more trust on the Marketplace</p>
                                        <div class="form-icon">
                                            <input name="url" id="twitter-url" type="url" class="form-control" value="https://twitter.com/streetboyyy">
                                        </div>
                                    </div>

                                    <div class="col-12 mb-4">
                                        <label class="form-label h6" for="website">Website</label>
                                        <div class="form-icon">
                                            <input name="url" id="web-url" type="url" class="form-control" value="https://streetboyyy.com/">
                                        </div>
                                    </div>
    
                                    <div class="col-12 mb-4">
                                        <label class="form-label h6" for="email">Email</label>
                                        <input name="email" id="email" type="email" class="form-control" value="streetboyyy@example.com">
                                    </div>
                                </div>

                                
                                <div class="row">
                                    <div class="col-12">
                                        <button type="submit" id="submit" name="send" class="btn btn-primary rounded">Update Profile</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>

                    <div class="rounded shadow mt-4">
                        <div class="p-4 border-bottom">
                            <h5 class="mb-0">Account Notifications :</h5>
                        </div>

                        <div class="p-4">
                            <div class="d-flex justify-content-between pb-4">
                                <h6 class="mb-0">When someone mentions me</h6>
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" value="" id="noti1">
                                    <label class="form-check-label" for="noti1"></label>
                                </div>
                            </div>
                            <div class="d-flex justify-content-between py-4 border-top">
                                <h6 class="mb-0">When someone follows me</h6>
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" value="" checked id="noti2">
                                    <label class="form-check-label" for="noti2"></label>
                                </div>
                            </div>
                            <div class="d-flex justify-content-between py-4 border-top">
                                <h6 class="mb-0">When shares my activity</h6>
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" value="" id="noti3">
                                    <label class="form-check-label" for="noti3"></label>
                                </div>
                            </div>
                            <div class="d-flex justify-content-between py-4 border-top">
                                <h6 class="mb-0">When someone messages me</h6>
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" value="" id="noti4">
                                    <label class="form-check-label" for="noti4"></label>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="rounded shadow mt-4">
                        <div class="p-4 border-bottom">
                            <h5 class="mb-0">Marketing Notifications :</h5>
                        </div>

                        <div class="p-4">
                            <div class="d-flex justify-content-between pb-4">
                                <h6 class="mb-0">There is a sale or promotion</h6>
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" value="" id="noti5">
                                    <label class="form-check-label" for="noti5"></label>
                                </div>
                            </div>
                            <div class="d-flex justify-content-between py-4 border-top">
                                <h6 class="mb-0">Company news</h6>
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" value="" id="noti6">
                                    <label class="form-check-label" for="noti6"></label>
                                </div>
                            </div>
                            <div class="d-flex justify-content-between py-4 border-top">
                                <h6 class="mb-0">Weekly jobs</h6>
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" value="" checked id="noti7">
                                    <label class="form-check-label" for="noti7"></label>
                                </div>
                            </div>
                            <div class="d-flex justify-content-between py-4 border-top">
                                <h6 class="mb-0">Unsubscribe News</h6>
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" value="" checked id="noti8">
                                    <label class="form-check-label" for="noti8"></label>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="rounded shadow mt-4">
                        <div class="p-4 border-bottom">
                            <h5 class="mb-0 text-danger">Delete Account :</h5>
                        </div>

                        <div class="p-4">
                            <h6 class="mb-0">Do you want to delete the account? Please press below "Delete" button</h6>
                            <div class="mt-4">
                                <button class="btn btn-danger">Delete Account</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<Footer/>

// src/pages/nft/profile-setting.vue
<template>
    <div>
        <NftNavLight/>

        <section class="bg-half-170 d-table w-100" :style="{backgroundImage:`url(${bg})`}">
            <div class="bg-overlay bg-gradient-overlay"></div>
            <div class="container">
                <div class="row mt-5 justify-content-center">
                    <div class="col-12">
                        <div class="title-heading text-center">
                            <h5 class="heading fw-semibold mb-0 sub-heading text-white title-dark">Profile Setting</h5>
                        </div>
                    </div>
                </div>

                <div class="position-middle-bottom">
                    <nav aria-label="breadcrumb" class="d-block">
                        <ul class="breadcrumb breadcrumb-muted mb-0 p-0">
                            <li class="breadcrumb-item"><router-link to="/">Coral</router-link></li>
                            <li class="breadcrumb-item"><router-link to="/creators">Creators</router-link></li>
                            <li class="breadcrumb-item"><router-link to="/creator-profile">@StreetBoy</router-link></li>
                            <li class="breadcrumb-item active" aria-current="page">Profile Setting</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </section>

        <div class="position-relative">
            <div class="shape overflow-hidden text-white">
                <svg viewBox="0 0 2880 48" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M0 48H1437.5H2880V0H2160C1442.5 52 720 0 720 0H0V48Z" fill="currentColor"></path>
                </svg>
            </div>
        </div>

        <section class="section">
            <div class="container">
                <div class="row">
                    <div class="col-lg-9">
                        <h5>You can set preferred display name, create your branded profile URL and manage other personal settings.</h5>
                    </div>
                </div>
                <div class="row g-4">
                    <div class="col-lg-4 col-md-5 col-12">
                        <div class="profile-pic">
                            <input id="pro-img" name="profile-image" type="file" class="d-none" @change="handleChange($event)" />
                            <div class="position-relative d-inline-block">
                               <img :src="image" class="avatar avatar-medium img-thumbnail rounded-pill shadow-sm" id="profile-image" alt="">
                                <label class="icons position-absolute bottom-0 end-0" for="pro-img"><span class="btn btn-icon btn-sm btn-pills btn-primary"><i data-feather="camera" class="icons"></i></span></label>
                            </div>
                        </div>

                        <div class="mt-4">
                            <p class="text-muted mb-0">We recommend an image of at least 400X400. GIFs work too.</p>
                        </div>
                    </div>

                    <div class="col-lg-8 col-md-7 col-12">
                        <div class="ms-lg-5">
                            <div class="rounded shadow">
                                <div class="p-4 border-bottom">
                                    <h5 class="mb-0">Edit Profile :</h5>
                                </div>
    
                                <div class="p-4">
                                    <form class="profile-edit">
                                        <div class="row">
                                            <div class="col-12 mb-4">
                                                <label class="form-label h6">Display Name</label>
                                                <input name="name" id="first" type="text" class="form-control" value="streetboyyy">
                                            </div>
        
                                            <div class="col-12 mb-4">
                                                <label class="form-label h6">URL</label>
                                                <div class="form-icon">
                                                    <input name="url" id="Coral-url" type="url" class="form-control" value="https://Coral.exe/streetboyyy">
                                                </div>
                                            </div>
            
                                            <div class="col-12 mb-4">
                                                <label class="form-label h6">Bio</label>
                                                <textarea name="comments" id="comments" rows="3" class="form-control" placeholder="I'm a Digital Artist. Digital Art with over 3 years of experience. Experienced with all stages of the Art cycle for dynamic projects."></textarea>
                                            </div>
        
                                            <div class="col-12 mb-4">
                                                <label class="form-label h6">Twitter Account</label>
                                                <p class="text-muted">Link your twitter account to gain more trust on the Marketplace</p>
                                                <div class="form-icon">
                                                    <input name="url" id="twitter-url" type="url" class="form-control" value="https://twitter.com/streetboyyy">
                                                </div>
                                            </div>
        
                                            <div class="col-12 mb-4">
                                                <label class="form-label h6">Website</label>
                                                <div class="form-icon">
                                                    <input name="url" id="web-url" type="url" class="form-control" value="https://streetboyyy.com/">
                                                </div>
                                            </div>
            
                                            <div class="col-12 mb-4">
                                                <label class="form-label h6">Email</label>
                                                <input name="email" id="email" type="email" class="form-control" value="streetboyyy@example.com">
                                            </div>
                                        </div>
        
                                        
                                        <div class="row">
                                            <div class="col-12">
                                                <button type="submit" id="submit" name="send" class="btn btn-primary rounded">Update Profile</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
    
                            <div class="rounded shadow mt-4">
                                <div class="p-4 border-bottom">
                                    <h5 class="mb-0">Account Notifications :</h5>
                                </div>
    
                                <div class="p-4">
                                    <div class="d-flex justify-content-between pb-4">
                                        <h6 class="mb-0">When someone mentions me</h6>
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" value="" id="noti1">
                                            <label class="form-check-label" for="noti1"></label>
                                        </div>
                                    </div>
                                    <div class="d-flex justify-content-between py-4 border-top">
                                        <h6 class="mb-0">When someone follows me</h6>
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" value="" checked id="noti2">
                                            <label class="form-check-label" for="noti2"></label>
                                        </div>
                                    </div>
                                    <div class="d-flex justify-content-between py-4 border-top">
                                        <h6 class="mb-0">When shares my activity</h6>
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" value="" id="noti3">
                                            <label class="form-check-label" for="noti3"></label>
                                        </div>
                                    </div>
                                    <div class="d-flex justify-content-between py-4 border-top">
                                        <h6 class="mb-0">When someone messages me</h6>
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" value="" id="noti4">
                                            <label class="form-check-label" for="noti4"></label>
                                        </div>
                                    </div>
                                </div>
                            </div>
    
                            <div class="rounded shadow mt-4">
                                <div class="p-4 border-bottom">
                                    <h5 class="mb-0">Marketing Notifications :</h5>
                                </div>
    
                                <div class="p-4">
                                    <div class="d-flex justify-content-between pb-4">
                                        <h6 class="mb-0">There is a sale or promotion</h6>
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" value="" id="noti5">
                                            <label class="form-check-label" for="noti5"></label>
                                        </div>
                                    </div>
                                    <div class="d-flex justify-content-between py-4 border-top">
                                        <h6 class="mb-0">Company news</h6>
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" value="" id="noti6">
                                            <label class="form-check-label" for="noti6"></label>
                                        </div>
                                    </div>
                                    <div class="d-flex justify-content-between py-4 border-top">
                                        <h6 class="mb-0">Weekly jobs</h6>
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" value="" checked id="noti7">
                                            <label class="form-check-label" for="noti7"></label>
                                        </div>
                                    </div>
                                    <div class="d-flex justify-content-between py-4 border-top">
                                        <h6 class="mb-0">Unsubscribe News</h6>
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" value="" checked id="noti8">
                                            <label class="form-check-label" for="noti8"></label>
                                        </div>
                                    </div>
                                </div>
                            </div>
    
                            <div class="rounded shadow mt-4">
                                <div class="p-4 border-bottom">
                                    <h5 class="mb-0 text-danger">Delete Account :</h5>
                                </div>
    
                                <div class="p-4">
                                    <h6 class="mb-0">Do you want to delete the account? Please press below "Delete" button</h6>
                                    <div class="mt-4">
                                        <button class="btn btn-danger">Delete Account</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <FooterOne/>

        <ScrollToTop/>

    </div>
</template>

<script setup>
    import bg from '@/assets/images/hero/pages.jpg'
    import NftNavLight from '@/components/navbar/nft-nav-light.vue';
    import FooterOne from '@/components/footer-one.vue';
    import ScrollToTop from '@/components/scroll-to-top.vue';

    import user from '@/assets/images/team/1.jpg'
    import { ref } from 'vue'
    let image = ref(user)

    const handleChange = (e) =>{
        e.preventDefault();
        image.value = URL.createObjectURL(e.target.files[0])
    }
</script>
