// __Coral_v1.2.0/React/Typescript/src/components/cta/nft-cta.tsx
import { Link } from 'react-router-dom'

import bg from '../../assets/images/hero/pages.jpg'
import image1 from '../../assets/images/community.png'
import image2 from '../../assets/images/united.png'

interface Cta{
    image: string;
    title: string;
    desc: string;
}

let data = [
    {
        image:image1,
        title:'Join our community: Coral',
        desc:'Welcome to the future, you can buy and sell awesome artworks form here.'
    },
    {
        image:image2,
        title:'Learn more about us: Coral',
        desc:'Welcome to the future, you can buy and sell awesome artworks form here.'
    },
]

export default function NftCta() {
  return (
        <section className="cta-video-section position-relative overflow-hidden" style={{backgroundImage:`url(${bg})`, backgroundAttachment:'fixed'}}>
            <div className="bg-overlay"></div>
            <div className="container">
                <div className="row justify-content-center">
                    <div className="col">
                        <div className="section-title text-center mb-4 pb-2">
                            <h4 className="title text-white title-dark mb-3">Join the fastest growing Coral NFTs</h4>
                            <p className="text-white-50 para-desc mb-0 mx-auto">Welcome to the future, you can buy and sell awesome artworks form here. The world largest digital marketplace for non-fungible tokens.</p>
                        </div>
                    </div>
                </div>

                <div className="row g-4">
                    {data.map((item:Cta,index:number)=>( 
                        <div className="col-md-6" key={index}>
                            <div className="card p-4 rounded-md shadow bg-white">
                                <h4 className="mb-4">{item.title}</h4>
                                <p className="text-muted mb-0">{item.desc}</p>

                                <div className="mt-3">
                                    <Link to="/aboutus" className="btn btn-link primary text-dark">Read More <i className="mdi mdi-arrow-right"></i></Link>
                                </div>
                                <div className="py-4"></div>
                                <div className="position-absolute bottom-0 end-0">
                                    <img src={item.image} className="avatar avatar-medium opacity-25" alt=""/>
                                </div>
                            </div>
                        </div>
                    ))}
                </div>
            </div>
        </section>
  )
}

// src/components/nft/nft-cta.vue
<template>
    <section class="cta-video-section position-relative overflow-hidden" :style="{backgroundImage:`url(${bg})`, backgroundAttachment:'fixed'}">
        <div class="bg-overlay"></div>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col">
                    <div class="section-title text-center mb-4 pb-2">
                        <h4 class="title text-white title-dark mb-3">Join the fastest growing Coral NFTs</h4>
                        <p class="text-white-50 para-desc mb-0 mx-auto">Welcome to the future, you can buy and sell awesome artworks form here. The world largest digital marketplace for non-fungible tokens.</p>
                    </div>
                </div>
            </div>

            <div class="row g-4">
                <div v-for="(item, index) in data" :key="index" class="col-md-6">
                    <div class="card p-4 rounded-md shadow bg-white">
                        <h4 class="mb-4">{{item.title}}</h4>
                        <p class="text-muted mb-0">{{item.desc}}</p>

                        <div class="mt-3">
                            <router-link to="/aboutus" class="btn btn-link primary text-dark">Read More <i class="mdi mdi-arrow-right"></i></router-link>
                        </div>
                        <div class="py-4"></div>
                        <div class="position-absolute bottom-0 end-0">
                            <img :src="item.image" class="avatar avatar-medium opacity-25" alt="">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</template>

<script setup>
    import { ref } from 'vue'

    import bg from '@/assets/images/hero/pages.jpg'
    
    import about1 from '@/assets/images/community.png'
    import about2 from '@/assets/images/united.png'

    let data = ref([
        {
            image:about1,
            title:'Join our community: Coral',
            desc:`Welcome to the future, you can buy and sell awesome artworks form here.`
        },
        {
            image:about2,
            title:'Learn more about us: Coral',
            desc:`Welcome to the future, you can buy and sell awesome artworks form here.`
        },
    ])
</script>
