// __Coral_v1.2.0/Svelte/src/pages/utility/privacy.svelte
<script>
    import bg from "../../assets/images/hero/pages.jpg";
    import { Link } from "svelte-routing";
    import Navlight from "../../components/navbar/navlight.svelte";
    import Footer from "../../components/footer.svelte";

</script>

<Navlight/>

<section class="bg-half-170 d-table w-100" style="background: url({bg}) center;">
    <div class="bg-overlay bg-gradient-overlay"></div>
    <div class="container">
        <div class="row mt-5 justify-content-center">
            <div class="col-12">
                <div class="title-heading text-center">
                    <h5 class="heading fw-semibold mb-0 sub-heading text-white title-dark">Privacy Policy</h5>
                </div>
            </div>
        </div>

        <div class="position-middle-bottom">
            <nav aria-label="breadcrumb" class="d-block">
                <ul class="breadcrumb breadcrumb-muted mb-0 p-0">
                    <li class="breadcrumb-item"><Link to="/">Coral</Link></li>
                    <li class="breadcrumb-item active" aria-current="page">Privacy Policy</li>
                </ul>
            </nav>
        </div>
    </div>
</section>

<div class="position-relative">
    <div class="shape overflow-hidden text-white">
        <svg viewBox="0 0 2880 48" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M0 48H1437.5H2880V0H2160C1442.5 52 720 0 720 0H0V48Z" fill="currentColor"></path>
        </svg>
    </div>
</div>

<section class="section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-9">
                <div class="card bg-light shadow border-0 rounded">
                    <div class="card-body">
                        <h5 class="card-title">Overview :</h5>
                        <p class="text-muted">It seems that only fragments of the original text remain in the Lorem Ipsum texts used today. One may speculate that over the course of time certain letters were added or deleted at various positions within the text.</p>
                        <p class="text-muted">In the 1960s, the text suddenly became known beyond the professional circle of typesetters and layout designers when it was used for Letraset sheets (adhesive letters on transparent film, popular until the 1980s) Versions of the text were subsequently included in DTP programmes such as PageMaker etc.</p>
                        <p class="text-muted">There is now an abundance of readable dummy texts. These are usually used when a text is required purely to fill a space. These alternatives to the classic Lorem Ipsum texts are often amusing and tell short, funny or nonsensical stories.</p>
                    
                        <h5 class="card-title">We use your information to :</h5>
                        <ul class="list-unstyled text-muted mt-3">
                            <li class="mt-2"><i data-feather="arrow-right" class="fea icon-sm me-2"></i>Digital Marketing Solutions for Tomorrow</li>
                            <li class="mt-2"><i data-feather="arrow-right" class="fea icon-sm me-2"></i>Our Talented & Experienced Marketing Agency</li>
                            <li class="mt-2"><i data-feather="arrow-right" class="fea icon-sm me-2"></i>Create your own skin to match your brand</li>
                            <li class="mt-2"><i data-feather="arrow-right" class="fea icon-sm me-2"></i>Digital Marketing Solutions for Tomorrow</li>
                            <li class="mt-2"><i data-feather="arrow-right" class="fea icon-sm me-2"></i>Our Talented & Experienced Marketing Agency</li>
                            <li class="mt-2"><i data-feather="arrow-right" class="fea icon-sm me-2"></i>Create your own skin to match your brand</li>
                        </ul>

                        <h5 class="card-title mt-3">Information Provided Voluntarily :</h5>
                        <p class="text-muted">In the 1960s, the text suddenly became known beyond the professional circle of typesetters and layout designers when it was used for Letraset sheets (adhesive letters on transparent film, popular until the 1980s) Versions of the text were subsequently included in DTP programmes such as PageMaker etc.</p>

                        <a href="#!" class="btn btn-primary">Print</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<Footer/>

// __Coral_v1.2.0/Nuxt/app/pages/privacy.vue
<template>
    <div>
        <NavLight/>

        <section class="bg-half-170 d-table w-100" :style="{backgroundImage:`url(${bg})`, backgroundPosition:'center'}">
            <div class="bg-overlay bg-gradient-overlay"></div>
            <div class="container">
                <div class="row mt-5 justify-content-center">
                    <div class="col-12">
                        <div class="title-heading text-center">
                            <h5 class="heading fw-semibold mb-0 sub-heading text-white title-dark">Privacy Policy</h5>
                        </div>
                    </div>
                </div>

                <div class="position-middle-bottom">
                    <nav aria-label="breadcrumb" class="d-block">
                        <ul class="breadcrumb breadcrumb-muted mb-0 p-0">
                            <li class="breadcrumb-item"><NuxtLink to="/">Coral</NuxtLink></li>
                            <li class="breadcrumb-item active" aria-current="page">Privacy Policy</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </section>

        <div class="position-relative">
            <div class="shape overflow-hidden text-white">
                <svg viewBox="0 0 2880 48" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M0 48H1437.5H2880V0H2160C1442.5 52 720 0 720 0H0V48Z" fill="currentColor"></path>
                </svg>
            </div>
        </div>

        <section class="section">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-9">
                        <div class="card bg-light shadow border-0 rounded">
                            <div class="card-body">
                                <h5 class="card-title">Overview :</h5>
                                <p class="text-muted">It seems that only fragments of the original text remain in the Lorem Ipsum texts used today. One may speculate that over the course of time certain letters were added or deleted at various positions within the text.</p>
                                <p class="text-muted">In the 1960s, the text suddenly became known beyond the professional circle of typesetters and layout designers when it was used for Letraset sheets (adhesive letters on transparent film, popular until the 1980s) Versions of the text were subsequently included in DTP programmes such as PageMaker etc.</p>
                                <p class="text-muted">There is now an abundance of readable dummy texts. These are usually used when a text is required purely to fill a space. These alternatives to the classic Lorem Ipsum texts are often amusing and tell short, funny or nonsensical stories.</p>
                            
                                <h5 class="card-title">We use your information to :</h5>
                                <ul class="list-unstyled text-muted mt-3">
                                    <li class="mt-2"><i data-feather="arrow-right" class="fea icon-sm me-2"></i>Digital Marketing Solutions for Tomorrow</li>
                                    <li class="mt-2"><i data-feather="arrow-right" class="fea icon-sm me-2"></i>Our Talented & Experienced Marketing Agency</li>
                                    <li class="mt-2"><i data-feather="arrow-right" class="fea icon-sm me-2"></i>Create your own skin to match your brand</li>
                                    <li class="mt-2"><i data-feather="arrow-right" class="fea icon-sm me-2"></i>Digital Marketing Solutions for Tomorrow</li>
                                    <li class="mt-2"><i data-feather="arrow-right" class="fea icon-sm me-2"></i>Our Talented & Experienced Marketing Agency</li>
                                    <li class="mt-2"><i data-feather="arrow-right" class="fea icon-sm me-2"></i>Create your own skin to match your brand</li>
                                </ul>
    
                                <h5 class="card-title mt-3">Information Provided Voluntarily :</h5>
                                <p class="text-muted">In the 1960s, the text suddenly became known beyond the professional circle of typesetters and layout designers when it was used for Letraset sheets (adhesive letters on transparent film, popular until the 1980s) Versions of the text were subsequently included in DTP programmes such as PageMaker etc.</p>
    
                                <NuxtLink to="#" class="btn btn-primary">Print</NuxtLink>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <FooterOne/>

        <ScrollToTop/>
    </div>
</template>

<script setup>
    import bg from '@/assets/images/hero/pages.jpg'
    import NavLight from '@/components/navbar/nav-light.vue';
</script>
