// __Coral_v1.2.0/Svelte/src/pages/auth/signup.svelte
<script>
    import { Link } from 'svelte-routing';
    import bg from '../../assets/images/hero/auth.jpg'
    import logo from '../../assets/images/logo-dark.png'
</script>

<section class="bg-home d-flex align-items-center" style="background: url({bg}) center;">
    <div class="bg-overlay bg-linear-gradient-2"></div>
    <div class="container">
        <div class="row justify-content-end">
            <div class="col-lg-4 col-md-6 col-12">
                <div class="p-4 bg-white rounded shadow-md mx-auto w-100" style="max-width: 400px;">
                    <form>
                        <Link to="/"><img src={logo} class="mb-4 d-block mx-auto" alt=""></Link>
                        <h6 class="mb-3 text-uppercase fw-semibold">Register your account</h6>
                    
                        <div class="mb-3">
                            <label class="form-label fw-semibold" for="name">Your Name</label>
                            <input name="name" id="name" type="text" class="form-control" placeholder="Calvin Carlo">
                        </div>

                        <div class="mb-3">
                            <label class="form-label fw-semibold" for="mail">Your Email</label>
                            <input name="email" id="email" type="email" class="form-control" placeholder="example@website.com">
                        </div>

                        <div class="mb-3">
                            <label class="form-label fw-semibold" for="loginpass">Password</label>
                            <input type="password" class="form-control" id="loginpass" placeholder="Password">
                        </div>
                    
                        <div class="form-check mb-3">
                            <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
                            <label class="form-label form-check-label text-muted" for="flexCheckDefault">I Accept <a href="#!" class="text-primary">Terms And Condition</a></label>
                        </div>
        
                        <button class="btn btn-primary w-100" type="submit">Register</button>

                        <div class="col-12 text-center mt-3">
                            <span><span class="text-muted small me-2">Already have an account ? </span> <Link to="/login" class="text-dark fw-semibold small">Sign in</Link></span>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

// __Coral_v1.2.0/Nuxt/app/pages/signup.vue
<template>
    <section class="bg-home d-flex align-items-center" :style="{backgroundImage:`url(${bg})`, backgroundPosition:'center'}">
        <div class="bg-overlay bg-linear-gradient-2"></div>
        <div class="container">
            <div class="row justify-content-end">
                <div class="col-lg-4 col-md-6 col-12">
                    <div class="p-4 bg-white rounded shadow-md mx-auto w-100" style="max-width: 400px;">
                        <form>
                            <NuxtLink to="/"><img :src="logo" class="mb-4 d-block mx-auto" alt=""></NuxtLink>
                            <h6 class="mb-3 text-uppercase fw-semibold">Register your account</h6>
                        
                            <div class="mb-3">
                                <label class="form-label fw-semibold">Your Name</label>
                                <input name="name" id="name" type="text" class="form-control" placeholder="Calvin Carlo">
                            </div>

                            <div class="mb-3">
                                <label class="form-label fw-semibold">Your Email</label>
                                <input name="email" id="email" type="email" class="form-control" placeholder="example@website.com">
                            </div>

                            <div class="mb-3">
                                <label class="form-label fw-semibold" for="loginpass">Password</label>
                                <input type="password" class="form-control" id="loginpass" placeholder="Password">
                            </div>
                        
                            <div class="form-check mb-3">
                                <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
                                <label class="form-label form-check-label text-muted" for="flexCheckDefault">I Accept <NuxtLink to="#" class="text-primary">Terms And Condition</NuxtLink></label>
                            </div>
            
                            <button class="btn btn-primary w-100" type="submit">Register</button>

                            <div class="col-12 text-center mt-3">
                                <span><span class="text-muted small me-2">Already have an account ? </span> <NuxtLink to="/login" class="text-dark fw-semibold small">Sign in</NuxtLink></span>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
</template>

<script setup>
import bg from '@/assets/images/hero/auth.jpg'
import logo from '@/assets/images/logo-dark.png'

</script>
