// __Coral_v1.2.0/Svelte/src/pages/utility/terms.svelte
<script>
    import bg from "../../assets/images/hero/pages.jpg";
    import { Link } from "svelte-routing";
    import Navlight from "../../components/navbar/navlight.svelte";
    import FaqOne from "../../components/faq-one.svelte";
    import Footer from "../../components/footer.svelte";

</script>

<Navlight/>

<section class="bg-half-170 d-table w-100" style="background: url({bg}) center;">
    <div class="bg-overlay bg-gradient-overlay"></div>
    <div class="container">
        <div class="row mt-5 justify-content-center">
            <div class="col-12">
                <div class="title-heading text-center">
                    <h5 class="heading fw-semibold mb-0 sub-heading text-white title-dark">Terms & Conditions</h5>
                </div>
            </div>
        </div>

        <div class="position-middle-bottom">
            <nav aria-label="breadcrumb" class="d-block">
                <ul class="breadcrumb breadcrumb-muted mb-0 p-0">
                    <li class="breadcrumb-item"><Link to="/">Coral</Link></li>
                    <li class="breadcrumb-item active" aria-current="page">Terms</li>
                </ul>
            </nav>
        </div>
    </div>
</section>

<div class="position-relative">
    <div class="shape overflow-hidden text-white">
        <svg viewBox="0 0 2880 48" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M0 48H1437.5H2880V0H2160C1442.5 52 720 0 720 0H0V48Z" fill="currentColor"></path>
        </svg>
    </div>
</div>

<section class="section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-9">
                <div class="card bg-light shadow border-0 rounded">
                    <div class="card-body">
                        <h5 class="card-title">Introduction :</h5>
                        <p class="text-muted">It seems that only fragments of the original text remain in the Lorem Ipsum texts used today. One may speculate that over the course of time certain letters were added or deleted at various positions within the text.</p>

                        <h5 class="card-title">User Agreements :</h5>
                        <p class="text-muted">The most well-known dummy text is the 'Lorem Ipsum', which is said to have <b class="text-danger">originated</b> in the 16th century. Lorem Ipsum is <b class="text-danger">composed</b> in a pseudo-Latin language which more or less <b class="text-danger">corresponds</b> to 'proper' Latin. It contains a series of real Latin words. This ancient dummy text is also <b class="text-danger">incomprehensible</b>, but it imitates the rhythm of most European languages in Latin script. The <b class="text-danger">advantage</b> of its Latin origin and the relative <b class="text-danger">meaninglessness</b> of Lorum Ipsum is that the text does not attract attention to itself or distract the viewer's <b class="text-danger">attention</b> from the layout.</p>
                        <p class="text-muted">There is now an <b class="text-danger">abundance</b> of readable dummy texts. These are usually used when a text is <b class="text-danger">required purely</b> to fill a space. These alternatives to the classic Lorem Ipsum texts are often amusing and tell short, funny or <b class="text-danger">nonsensical</b> stories.</p>
                        <p class="text-muted">It seems that only <b class="text-danger">fragments</b> of the original text remain in the Lorem Ipsum texts used today. One may speculate that over the course of time certain letters were added or deleted at various positions within the text.</p>
                        
                        <h5 class="card-title">Restrictions :</h5>
                        <p class="text-muted">You are specifically restricted from all of the following :</p>
                        <ul class="list-unstyled text-muted">
                            <li class="mt-2"><i data-feather="arrow-right" class="fea icon-sm me-2"></i>Digital Marketing Solutions for Tomorrow</li>
                            <li class="mt-2"><i data-feather="arrow-right" class="fea icon-sm me-2"></i>Our Talented & Experienced Marketing Agency</li>
                            <li class="mt-2"><i data-feather="arrow-right" class="fea icon-sm me-2"></i>Create your own skin to match your brand</li>
                            <li class="mt-2"><i data-feather="arrow-right" class="fea icon-sm me-2"></i>Digital Marketing Solutions for Tomorrow</li>
                            <li class="mt-2"><i data-feather="arrow-right" class="fea icon-sm me-2"></i>Our Talented & Experienced Marketing Agency</li>
                            <li class="mt-2"><i data-feather="arrow-right" class="fea icon-sm me-2"></i>Create your own skin to match your brand</li>
                        </ul>

                        <h5 class="card-title">Users Question & Answer :</h5>
                        
                        <FaqOne/>

                        <div class="mt-3">
                            <a href="#!" class="btn btn-primary mt-2 me-2">Accept</a>
                            <a href="#!" class="btn btn-outline-primary mt-2">Decline</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<Footer/>

// __Coral_v1.2.0/Nuxt/app/pages/terms.vue
<template>
    <div>
        <NavLight/>

        <section class="bg-half-170 d-table w-100" :style="{backgroundImage:`url(${bg})`, backgroundPosition:'center'}">
            <div class="bg-overlay bg-gradient-overlay"></div>
            <div class="container">
                <div class="row mt-5 justify-content-center">
                    <div class="col-12">
                        <div class="title-heading text-center">
                            <h5 class="heading fw-semibold mb-0 sub-heading text-white title-dark">Terms & Conditions</h5>
                        </div>
                    </div>
                </div>

                <div class="position-middle-bottom">
                    <nav aria-label="breadcrumb" class="d-block">
                        <ul class="breadcrumb breadcrumb-muted mb-0 p-0">
                            <li class="breadcrumb-item"><NuxtLink to="/">Coral</NuxtLink></li>
                            <li class="breadcrumb-item active" aria-current="page">Terms</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </section>

        <div class="position-relative">
            <div class="shape overflow-hidden text-white">
                <svg viewBox="0 0 2880 48" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M0 48H1437.5H2880V0H2160C1442.5 52 720 0 720 0H0V48Z" fill="currentColor"></path>
                </svg>
            </div>
        </div>

        <section class="section">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-9">
                        <div class="card bg-light shadow border-0 rounded">
                            <div class="card-body">
                                <h5 class="card-title">Introduction :</h5>
                                <p class="text-muted">It seems that only fragments of the original text remain in the Lorem Ipsum texts used today. One may speculate that over the course of time certain letters were added or deleted at various positions within the text.</p>

                                <h5 class="card-title">User Agreements :</h5>
                                <p class="text-muted">The most well-known dummy text is the 'Lorem Ipsum', which is said to have <b class="text-danger">originated</b> in the 16th century. Lorem Ipsum is <b class="text-danger">composed</b> in a pseudo-Latin language which more or less <b class="text-danger">corresponds</b> to 'proper' Latin. It contains a series of real Latin words. This ancient dummy text is also <b class="text-danger">incomprehensible</b>, but it imitates the rhythm of most European languages in Latin script. The <b class="text-danger">advantage</b> of its Latin origin and the relative <b class="text-danger">meaninglessness</b> of Lorum Ipsum is that the text does not attract attention to itself or distract the viewer's <b class="text-danger">attention</b> from the layout.</p>
                                <p class="text-muted">There is now an <b class="text-danger">abundance</b> of readable dummy texts. These are usually used when a text is <b class="text-danger">required purely</b> to fill a space. These alternatives to the classic Lorem Ipsum texts are often amusing and tell short, funny or <b class="text-danger">nonsensical</b> stories.</p>
                                <p class="text-muted">It seems that only <b class="text-danger">fragments</b> of the original text remain in the Lorem Ipsum texts used today. One may speculate that over the course of time certain letters were added or deleted at various positions within the text.</p>
                                
                                <h5 class="card-title">Restrictions :</h5>
                                <p class="text-muted">You are specifically restricted from all of the following :</p>
                                <ul class="list-unstyled text-muted">
                                    <li class="mt-2"><i data-feather="arrow-right" class="fea icon-sm me-2"></i>Digital Marketing Solutions for Tomorrow</li>
                                    <li class="mt-2"><i data-feather="arrow-right" class="fea icon-sm me-2"></i>Our Talented & Experienced Marketing Agency</li>
                                    <li class="mt-2"><i data-feather="arrow-right" class="fea icon-sm me-2"></i>Create your own skin to match your brand</li>
                                    <li class="mt-2"><i data-feather="arrow-right" class="fea icon-sm me-2"></i>Digital Marketing Solutions for Tomorrow</li>
                                    <li class="mt-2"><i data-feather="arrow-right" class="fea icon-sm me-2"></i>Our Talented & Experienced Marketing Agency</li>
                                    <li class="mt-2"><i data-feather="arrow-right" class="fea icon-sm me-2"></i>Create your own skin to match your brand</li>
                                </ul>

                                <h5 class="card-title">Users Question & Answer :</h5>
                                
                                <FaqOne/>

                                <div class="mt-3">
                                    <NuxtLink to="#" class="btn btn-primary mt-2 me-2">Accept</NuxtLink>
                                    <NuxtLink to="#" class="btn btn-outline-primary mt-2">Decline</NuxtLink>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <FooterOne/>

        <ScrollToTop/>
    </div>
</template>

<script setup>
    import bg from '@/assets/images/hero/pages.jpg';
    import NavLight from '@/components/navbar/nav-light.vue';
</script>
