// __Coral_v1.2.0/Next/Javascript/src/app/wallet/page.jsx
import Link from 'next/link'
import Image from 'next/image'

import { wallet } from '../data/data'

import Footer from '../components/footer'
import NftNavLight from '../components/navbar/nft-nav-light'
import ScrollToTop from '../components/scroll-to-top'

export default function Wallet() {
  return (
    <>
        <NftNavLight/>   

        <section className="bg-half-170 d-table w-100" style={{backgroundImage:`url('/images/hero/pages.jpg')`, backgroundPosition:'center'}}>
            <div className="bg-overlay bg-gradient-overlay"></div>
            <div className="container">
                <div className="row mt-5 justify-content-center">
                    <div className="col-12">
                        <div className="title-heading text-center">
                            <h5 className="heading fw-semibold mb-0 sub-heading text-white title-dark">Wallets</h5>
                        </div>
                    </div>
                </div>

                <div className="position-middle-bottom">
                    <nav aria-label="breadcrumb" className="d-block">
                        <ul className="breadcrumb breadcrumb-muted mb-0 p-0">
                            <li className="breadcrumb-item"><Link href="/">Coral</Link></li>
                            <li className="breadcrumb-item active" aria-current="page">Wallet</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </section>

        <div className="position-relative">
            <div className="shape overflow-hidden text-white">
                <svg viewBox="0 0 2880 48" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M0 48H1437.5H2880V0H2160C1442.5 52 720 0 720 0H0V48Z" fill="currentColor"></path>
                </svg>
            </div>
        </div>

        <section className="section">
            <div className="container">
                <div className="row g-4">
                    {wallet.map((item,index)=>( 
                        <div className="col-lg-3 col-md-4 col-sm-6 col-12" key={index}>
                            <div className="wallet position-relative overflow-hidden rounded shadow">
                                <div className="bg-gradient-primary p-4"></div>
                                <div className="position-relative">
                                    <div className="position-absolute top-0 start-50 translate-middle">
                                        <Image src={item.image} width={65} height={65} className="avatar avatar-small rounded-pill shadow-sm p-2 bg-light" alt=""/>
                                    </div>
                                    
                                    <div className="content text-center p-4">
                                        <h5 className="mt-4 mb-0">{item.name}</h5>
                                        <p className="text-muted mt-3 mb-0">Learn about how to get the wallet and much more clicking <a href="javascript:void(0)" className="text-primary">here <i className="mdi mdi-arrow-right"></i></a></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    ))}
                </div>
            </div>
        </section>

        <Footer/>

        <ScrollToTop/>
    </>
  )
}

// __Coral_v1.2.0/Nuxt/app/pages/wallet.vue
<template>
    <div>
        <NftNavLight/>

        <section class="bg-half-170 d-table w-100" :style="{backgroundImage:`url(${bg})`, backgroundPosition:'center'}">
            <div class="bg-overlay bg-gradient-overlay"></div>
            <div class="container">
                <div class="row mt-5 justify-content-center">
                    <div class="col-12">
                        <div class="title-heading text-center">
                            <h5 class="heading fw-semibold mb-0 sub-heading text-white title-dark">Wallets</h5>
                        </div>
                    </div>
                </div>

                <div class="position-middle-bottom">
                    <nav aria-label="breadcrumb" class="d-block">
                        <ul class="breadcrumb breadcrumb-muted mb-0 p-0">
                            <li class="breadcrumb-item"><NuxtLink to="/">Coral</NuxtLink></li>
                            <li class="breadcrumb-item active" aria-current="page">Wallet</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </section>

        <div class="position-relative">
            <div class="shape overflow-hidden text-white">
                <svg viewBox="0 0 2880 48" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M0 48H1437.5H2880V0H2160C1442.5 52 720 0 720 0H0V48Z" fill="currentColor"></path>
                </svg>
            </div>
        </div>

        <section class="section">
            <div class="container">
                <div class="row g-4">
                    <div v-for="(item, index) in wallet" :key="index" class="col-lg-3 col-md-4 col-sm-2 col-12">
                        <div class="wallet position-relative overflow-hidden rounded shadow">
                            <div class="bg-gradient-primary p-4"></div>
                            <div class="position-relative">
                                <div class="position-absolute top-0 start-50 translate-middle">
                                    <img :src="item.image" class="avatar avatar-small rounded-pill shadow-sm p-2 bg-light" alt="">
                                </div>
                                
                                <div class="content text-center p-4">
                                    <h5 class="mt-4 mb-0">{{item.name}}</h5>
                                    <p class="text-muted mt-3 mb-0">Learn about how to get the wallet and much more clicking <NuxtLink to="#" class="text-primary">here <i class="mdi mdi-arrow-right"></i></NuxtLink></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <FooterOne/>

        <ScrollToTop/>
    </div>
</template>

<script setup>
    import bg from '@/assets/images/hero/pages.jpg'
    import NftNavLight from '@/components/navbar/nft-nav-light.vue';
    import { wallet } from '@/data/data';
</script>
