// __Coral_v1.2.0/React/Typescript/src/pages/blog/blog-link-post.tsx
import { Link } from 'react-router-dom'

import bg from '../../assets/images/hero/pages.jpg'

import Navlight from '../../components/navbar/navlight'
import SidebarBlog from '../../components/blog/sidebar-blog'
import BlogComment from '../../components/blog/blog-comment'
import BlogDesc from '../../components/blog/blog-desc'
import Footer from '../../components/footer'
import ScrollToTop from '../../components/scroll-to-top'

export default function BlogLinkPost() {
  return (
    <>
        <Navlight/>

        <section className="bg-half-170 d-table w-100" style={{backgroundImage:`url(${bg})`, backgroundPosition:'center'}}>
            <div className="bg-overlay bg-gradient-overlay"></div>
            <div className="container">
                <div className="row mt-5 justify-content-center">
                    <div className="col-12">
                        <div className="title-heading text-center">
                            <span className="badge bg-primary">Templates & Themes</span>
                            <h5 className="heading fw-semibold mb-0 sub-heading text-white title-dark mt-4">Coral - Multipurpose Template</h5>

                            <ul className="list-inline text-center mb-0">
                                <li className="list-inline-item mx-4 mt-4">
                                    <span className="text-white-50 d-block">Author</span>
                                    <Link to="#" className="text-white title-dark">Coral</Link>
                                </li>

                                <li className="list-inline-item mx-4 mt-4">
                                    <span className="text-white-50 d-block">Date</span>
                                    <span className="text-white title-dark">15th July 2025</span>
                                </li>

                                <li className="list-inline-item mx-4 mt-4">
                                    <span className="text-white-50 d-block">Read Time</span>
                                    <span className="text-white title-dark">5 min read</span>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>

                <div className="position-middle-bottom">
                    <nav aria-label="breadcrumb" className="d-block">
                        <ul className="breadcrumb breadcrumb-muted mb-0 p-0">
                            <li className="breadcrumb-item"><Link to="/">Coral</Link></li>
                            <li className="breadcrumb-item"><Link to="/blogs">Blogs</Link></li>
                            <li className="breadcrumb-item active" aria-current="page">Coral - Multipurpose Template</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </section>
        <div className="position-relative">
            <div className="shape overflow-hidden text-white">
                <svg viewBox="0 0 2880 48" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M0 48H1437.5H2880V0H2160C1442.5 52 720 0 720 0H0V48Z" fill="currentColor"></path>
                </svg>
            </div>
        </div>

         <section className="section">
            <div className="container">
                <div className="row g-4">
                    <div className="col-lg-8 col-md-7">
                        <div className="card text-center border-0 shadow rounded overflow-hidden">
                            <div className="card-body">
                                <div className="bg-soft-primary rounded-3 p-4 mb-4">
                                    <Link to="#!" className="tag h6 text-decoration-underline">Templates & Themes</Link>
                                    <div className="position-relative my-3">
                                        <div className="p-3 rounded-circle d-inline-flex bg-white"><i className="mdi mdi-36px mdi-link-variant lh-1"></i></div>
                                    </div>

                                    <Link to="#!" className="title h4 text-dark">Coral - Multipurpose Template</Link>
                                    <p className="text-muted para-desc mx-auto mt-2">If the distribution of letters and 'words' is random, the reader will not be distracted from making a neutral judgement on the visual impact and readability of the typefaces.</p>
                                    
                                    <span className="text-muted mb-0">15th July 2025</span>
                                </div>
                                
                                <BlogDesc/>
                            </div>
                        </div>

                        <BlogComment/>
                    </div>

                    <div className="col-lg-4 col-md-5 col-12">
                        <SidebarBlog/>
                    </div>
                </div>
            </div>
        </section>

        <Footer/>

        <ScrollToTop/>
    </>
  )
}

// src/pages/blog/blog-link-post.vue
<template>
    <div>
        <NavLight/>

        <section class="bg-half-170 d-table w-100" :style="{backgroundImage:`url(${bg})`}">
            <div class="bg-overlay bg-gradient-overlay"></div>
            <div class="container">
                <div class="row mt-5 justify-content-center">
                    <div class="col-12">
                        <div class="title-heading text-center">
                            <span class="badge bg-primary">Templates & Themes</span>
                            <h5 class="heading fw-semibold mb-0 sub-heading text-white title-dark mt-4">Coral - Multipurpose Template</h5>

                            <ul class="list-inline text-center mb-0">
                                <li class="list-inline-item mx-4 mt-4">
                                    <span class="text-white-50 d-block">Author</span>
                                    <router-link to="#" class="text-white title-dark">Coral</router-link>
                                </li>

                                <li class="list-inline-item mx-4 mt-4">
                                    <span class="text-white-50 d-block">Date</span>
                                    <span class="text-white title-dark">15th July 2025</span>
                                </li>

                                <li class="list-inline-item mx-4 mt-4">
                                    <span class="text-white-50 d-block">Read Time</span>
                                    <span class="text-white title-dark">5 min read</span>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>

                <div class="position-middle-bottom">
                    <nav aria-label="breadcrumb" class="d-block">
                        <ul class="breadcrumb breadcrumb-muted mb-0 p-0">
                            <li class="breadcrumb-item"><router-link to="/">Coral</router-link></li>
                            <li class="breadcrumb-item"><router-link to="/blogs">Blogs</router-link></li>
                            <li class="breadcrumb-item active" aria-current="page">Coral - Multipurpose Template</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </section>

        <div class="position-relative">
            <div class="shape overflow-hidden text-white">
                <svg viewBox="0 0 2880 48" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M0 48H1437.5H2880V0H2160C1442.5 52 720 0 720 0H0V48Z" fill="currentColor"></path>
                </svg>
            </div>
        </div>

        <section class="section">
            <div class="container">
                <div class="row g-4">
                    <div class="col-lg-8 col-md-7">
                        <div class="card text-center border-0 shadow rounded overflow-hidden">
                            <div class="card-body p-0">
                                <div class="bg-soft-primary rounded-3 p-4 mb-4 m-4">
                                    <router-link to="#!" class="tag h6 text-decoration-underline">Templates & Themes</router-link>
                                    <div class="position-relative my-3">
                                        <div class="p-3 rounded-circle d-inline-flex bg-white"><i class="mdi mdi-36px mdi-link-variant lh-1"></i></div>
                                    </div>


                                    <router-link to="#!" class="title h4 text-dark">Coral - Multipurpose Template</router-link>
                                    <p class="text-muted para-desc mx-auto mt-2">If the distribution of letters and 'words' is random, the reader will not be distracted from making a neutral judgement on the visual impact and readability of the typefaces.</p>
                                    
                                    <span class="text-muted mb-0">15th July 2025</span>
                                </div>
                                
                                <BlogDesc/>
                            </div>
                        </div>

                        <BlogComment/>
                    </div>

                    <div class="col-lg-4 col-md-5 col-12">
                        <BlogsSidebar/>
                    </div>
                </div>
            </div>
        </section>
        <FooterOne/>

        <ScrollToTop/>
    </div>
</template>

<script setup>
import NavLight from '@/components/navbar/nav-light.vue';
import bg from '@/assets/images/hero/pages.jpg'
import BlogDesc from '@/components/blog/blog-desc.vue';
import BlogComment from '@/components/blog/blog-comment.vue';
import BlogsSidebar from '@/components/blog/blogs-sidebar.vue';
import FooterOne from '@/components/footer-one.vue';
import ScrollToTop from '@/components/scroll-to-top.vue';

</script>

<style lang="scss" scoped>

</style>
