// src/components/pricing-one.vue
<template>
    <div class="row g-4">
        <div class="col-lg-3 col-md-6 col-12">
            <div class="pricing bg-light rounded position-relative overflow-hidden shadow">
                <div class="price-header rounded-top p-4 pb-0">
                    <div class="position-relative features text-center mx-lg-4 px-md-1 my-4">
                        <div class="position-relative d-flex">
                            <i data-feather="log-in" class="fea icon-ex-md text-primary z-1"></i>
                            <div class="feature-icon bg-soft-primary position-absolute top-0 translate-middle"></div>
                        </div>
                    </div>
                    
                    <h4 class="mb-0">Free</h4>
                </div>
                <div class="d-flex p-4">
                    <span class="h5 mb-0">$</span>
                    <span class="price h2 mb-0 ms-1">0.00</span>
                    <span class="h5 align-self-end mb-1">/mo</span>
                </div>
                <div class="pricing-features text-start">
                    <ul class="feature list-unstyled p-4 pt-0 mb-0">
                        <li class="feature-list text-muted"><i data-feather="arrow-right-circle" class="fea icon-sm text-dark me-2"></i>Full Access</li>
                    </ul>
                    <div class="p-4 pt-0">
                        <router-link to="#" class="btn btn-soft-primary w-100">Free Signup</router-link>                                        
                    </div>
                </div>    
            </div>
        </div>

        <div class="col-lg-3 col-md-6 col-12">
            <div class="pricing bg-white rounded position-relative overflow-hidden shadow">
                <div class="price-header rounded-top p-4 pb-0">
                    <div class="position-relative features text-center mx-lg-4 px-md-1 my-4">
                        <div class="position-relative d-flex">
                            <i data-feather="airplay" class="fea icon-ex-md text-primary z-1"></i>
                            <div class="feature-icon bg-soft-primary position-absolute top-0 translate-middle"></div>
                        </div>
                    </div>

                    <h4 class="mb-0">Standerd</h4>
                </div>
                <div class="d-flex p-4">
                    <span class="h5 mb-0">$</span>
                    <span class="price h2 mb-0 ms-1">19.99</span>
                    <span class="h5 align-self-end mb-1">/mo</span>
                </div>
                <div class="pricing-features text-start">
                    <ul class="feature list-unstyled p-4 pt-0 mb-0">
                        <li class="feature-list text-muted"><i data-feather="arrow-right-circle" class="fea icon-sm text-dark me-2"></i>Full Access</li>
                        <li class="feature-list text-muted mt-2"><i data-feather="arrow-right-circle" class="fea icon-sm text-dark me-2"></i>Enhanced Security</li>
                        <li class="feature-list text-muted mt-2"><i data-feather="arrow-right-circle" class="fea icon-sm text-dark me-2"></i>Free Appointments</li>
                        <li class="feature-list text-muted mt-2"><i data-feather="arrow-right-circle" class="fea icon-sm text-dark me-2"></i>Free Installment</li>
                    </ul>
                    <div class="p-4 pt-0">
                        <router-link to="#" class="btn btn-soft-primary w-100">Buy Now</router-link>                                        
                    </div>
                </div>    
            </div>
        </div>
        
        <div class="col-lg-3 col-md-6 col-12">
            <div class="pricing bg-primary bg-gradient text-white rounded position-relative overflow-hidden shadow">
                <div class="price-header rounded-top p-4 pb-0">
                    <div class="position-relative features text-center mx-lg-4 px-md-1 my-4">
                        <div class="position-relative d-flex">
                            <i data-feather="award" class="fea icon-ex-md text-primary z-1"></i>
                            <div class="feature-icon bg-white position-absolute top-0 translate-middle"></div>
                        </div>
                    </div>

                    <h4 class="mb-0">Professional</h4>
                </div>
                <div class="d-flex p-4">
                    <span class="h5 mb-0">$</span>
                    <span class="price h2 mb-0 ms-1">99.99</span>
                    <span class="h5 align-self-end mb-1">/mo</span>
                </div>
                <div class="pricing-features text-start">
                    <ul class="feature list-unstyled p-4 pt-0 mb-0">
                        <li class="feature-list text-white-50"><i data-feather="arrow-right-circle" class="fea icon-sm text-white me-2"></i>Full Access</li>
                        <li class="feature-list text-white-50 mt-2"><i data-feather="arrow-right-circle" class="fea icon-sm text-white me-2"></i>Enhanced Security</li>
                        <li class="feature-list text-white-50 mt-2"><i data-feather="arrow-right-circle" class="fea icon-sm text-white me-2"></i>Source Files</li>
                        <li class="feature-list text-white-50 mt-2"><i data-feather="arrow-right-circle" class="fea icon-sm text-white me-2"></i>1 Domain Free</li>
                        <li class="feature-list text-white-50 mt-2"><i data-feather="arrow-right-circle" class="fea icon-sm text-white me-2"></i>Free Appointments</li>
                        <li class="feature-list text-white-50 mt-2"><i data-feather="arrow-right-circle" class="fea icon-sm text-white me-2"></i>Free Installment</li>
                    </ul>
                    <div class="p-4 pt-0">
                        <router-link to="#" class="btn btn-danger w-100">Subscribe Now</router-link>                                        
                    </div>
                </div>    
            </div>
        </div>
        
        <div class="col-lg-3 col-md-6 col-12">
            <div class="pricing bg-white rounded position-relative overflow-hidden shadow">
                <div class="price-header rounded-top p-4 pb-0">
                    <div class="position-relative features text-center mx-lg-4 px-md-1 my-4">
                        <div class="position-relative d-flex">
                            <i data-feather="star" class="fea icon-ex-md text-primary z-1"></i>
                            <div class="feature-icon bg-soft-primary position-absolute top-0 translate-middle"></div>
                        </div>
                    </div>

                    <h4 class="mb-0">Plus</h4>
                </div>
                <div class="d-flex p-4">
                    <span class="h5 mb-0">$</span>
                    <span class="price h2 mb-0 ms-1">199.99</span>
                    <span class="h5 align-self-end mb-1">/mo</span>
                </div>
                <div class="pricing-features text-start">
                    <ul class="feature list-unstyled p-4 pt-0 mb-0">
                        <li class="feature-list text-muted"><i data-feather="arrow-right-circle" class="fea icon-sm text-dark me-2"></i>Full Access</li>
                        <li class="feature-list text-muted mt-2"><i data-feather="arrow-right-circle" class="fea icon-sm text-dark me-2"></i>Enhanced Security</li>
                        <li class="feature-list text-muted mt-2"><i data-feather="arrow-right-circle" class="fea icon-sm text-dark me-2"></i>Source Files</li>
                        <li class="feature-list text-muted mt-2"><i data-feather="arrow-right-circle" class="fea icon-sm text-dark me-2"></i>10 Domain Free</li>
                        <li class="feature-list text-muted mt-2"><i data-feather="arrow-right-circle" class="fea icon-sm text-dark me-2"></i>Free Appointments</li>
                        <li class="feature-list text-muted mt-2"><i data-feather="arrow-right-circle" class="fea icon-sm text-dark me-2"></i>Free Installment</li>
                    </ul>
                    <div class="p-4 pt-0">
                        <router-link to="#" class="btn btn-soft-primary w-100">Subscribe Now</router-link>                                        
                    </div>
                </div>    
            </div>
        </div>
    </div>
</template>

<script setup>

</script>

// __Coral_v1.2.0/Svelte/src/components/pricing-one.svelte
<div class="row g-4">
    <div class="col-lg-3 col-md-6 col-12">
        <div class="pricing bg-light rounded position-relative overflow-hidden shadow">
            <div class="price-header rounded-top p-4 pb-0">
                <div class="position-relative features text-center mx-lg-4 px-md-1 my-4">
                    <div class="position-relative d-flex">
                        <i data-feather="log-in" class="fea icon-ex-md text-primary z-1"></i>
                        <div class="feature-icon bg-soft-primary position-absolute top-0 translate-middle"></div>
                    </div>
                </div>
                
                <h4 class="mb-0">Free</h4>
            </div>
            <div class="d-flex p-4">
                <span class="h5 mb-0">$</span>
                <span class="price h2 mb-0 ms-1">0.00</span>
                <span class="h5 align-self-end mb-1">/mo</span>
            </div>
            <div class="pricing-features text-start">
                <ul class="feature list-unstyled p-4 pt-0 mb-0">
                    <li class="feature-list text-muted"><i data-feather="arrow-right-circle" class="fea icon-sm text-dark me-2"></i>Full Access</li>
                </ul>
                <div class="p-4 pt-0">
                    <a href="#!" class="btn btn-soft-primary w-100">Free Signup</a>                                        
                </div>
            </div>    
        </div>
    </div>

    <div class="col-lg-3 col-md-6 col-12">
        <div class="pricing bg-white rounded position-relative overflow-hidden shadow">
            <div class="price-header rounded-top p-4 pb-0">
                <div class="position-relative features text-center mx-lg-4 px-md-1 my-4">
                    <div class="position-relative d-flex">
                        <i data-feather="airplay" class="fea icon-ex-md text-primary z-1"></i>
                        <div class="feature-icon bg-soft-primary position-absolute top-0 translate-middle"></div>
                    </div>
                </div>

                <h4 class="mb-0">Standerd</h4>
            </div>
            <div class="d-flex p-4">
                <span class="h5 mb-0">$</span>
                <span class="price h2 mb-0 ms-1">19.99</span>
                <span class="h5 align-self-end mb-1">/mo</span>
            </div>
            <div class="pricing-features text-start">
                <ul class="feature list-unstyled p-4 pt-0 mb-0">
                    <li class="feature-list text-muted"><i data-feather="arrow-right-circle" class="fea icon-sm text-dark me-2"></i>Full Access</li>
                    <li class="feature-list text-muted mt-2"><i data-feather="arrow-right-circle" class="fea icon-sm text-dark me-2"></i>Enhanced Security</li>
                    <li class="feature-list text-muted mt-2"><i data-feather="arrow-right-circle" class="fea icon-sm text-dark me-2"></i>Free Appointments</li>
                    <li class="feature-list text-muted mt-2"><i data-feather="arrow-right-circle" class="fea icon-sm text-dark me-2"></i>Free Installment</li>
                </ul>
                <div class="p-4 pt-0">
                    <a href="#!" class="btn btn-soft-primary w-100">Buy Now</a>                                        
                </div>
            </div>    
        </div>
    </div>
    
    <div class="col-lg-3 col-md-6 col-12">
        <div class="pricing bg-primary bg-gradient text-white rounded position-relative overflow-hidden shadow">
            <div class="price-header rounded-top p-4 pb-0">
                <div class="position-relative features text-center mx-lg-4 px-md-1 my-4">
                    <div class="position-relative d-flex">
                        <i data-feather="award" class="fea icon-ex-md text-primary z-1"></i>
                        <div class="feature-icon bg-white position-absolute top-0 translate-middle"></div>
                    </div>
                </div>

                <h4 class="mb-0">Professional</h4>
            </div>
            <div class="d-flex p-4">
                <span class="h5 mb-0">$</span>
                <span class="price h2 mb-0 ms-1">99.99</span>
                <span class="h5 align-self-end mb-1">/mo</span>
            </div>
            <div class="pricing-features text-start">
                <ul class="feature list-unstyled p-4 pt-0 mb-0">
                    <li class="feature-list text-white-50"><i data-feather="arrow-right-circle" class="fea icon-sm text-white me-2"></i>Full Access</li>
                    <li class="feature-list text-white-50 mt-2"><i data-feather="arrow-right-circle" class="fea icon-sm text-white me-2"></i>Enhanced Security</li>
                    <li class="feature-list text-white-50 mt-2"><i data-feather="arrow-right-circle" class="fea icon-sm text-white me-2"></i>Source Files</li>
                    <li class="feature-list text-white-50 mt-2"><i data-feather="arrow-right-circle" class="fea icon-sm text-white me-2"></i>1 Domain Free</li>
                    <li class="feature-list text-white-50 mt-2"><i data-feather="arrow-right-circle" class="fea icon-sm text-white me-2"></i>Free Appointments</li>
                    <li class="feature-list text-white-50 mt-2"><i data-feather="arrow-right-circle" class="fea icon-sm text-white me-2"></i>Free Installment</li>
                </ul>
                <div class="p-4 pt-0">
                    <a href="#!" class="btn btn-danger w-100">Subscribe Now</a>                                        
                </div>
            </div>    
        </div>
    </div>
    
    <div class="col-lg-3 col-md-6 col-12">
        <div class="pricing bg-white rounded position-relative overflow-hidden shadow">
            <div class="price-header rounded-top p-4 pb-0">
                <div class="position-relative features text-center mx-lg-4 px-md-1 my-4">
                    <div class="position-relative d-flex">
                        <i data-feather="star" class="fea icon-ex-md text-primary z-1"></i>
                        <div class="feature-icon bg-soft-primary position-absolute top-0 translate-middle"></div>
                    </div>
                </div>

                <h4 class="mb-0">Plus</h4>
            </div>
            <div class="d-flex p-4">
                <span class="h5 mb-0">$</span>
                <span class="price h2 mb-0 ms-1">199.99</span>
                <span class="h5 align-self-end mb-1">/mo</span>
            </div>
            <div class="pricing-features text-start">
                <ul class="feature list-unstyled p-4 pt-0 mb-0">
                    <li class="feature-list text-muted"><i data-feather="arrow-right-circle" class="fea icon-sm text-dark me-2"></i>Full Access</li>
                    <li class="feature-list text-muted mt-2"><i data-feather="arrow-right-circle" class="fea icon-sm text-dark me-2"></i>Enhanced Security</li>
                    <li class="feature-list text-muted mt-2"><i data-feather="arrow-right-circle" class="fea icon-sm text-dark me-2"></i>Source Files</li>
                    <li class="feature-list text-muted mt-2"><i data-feather="arrow-right-circle" class="fea icon-sm text-dark me-2"></i>10 Domain Free</li>
                    <li class="feature-list text-muted mt-2"><i data-feather="arrow-right-circle" class="fea icon-sm text-dark me-2"></i>Free Appointments</li>
                    <li class="feature-list text-muted mt-2"><i data-feather="arrow-right-circle" class="fea icon-sm text-dark me-2"></i>Free Installment</li>
                </ul>
                <div class="p-4 pt-0">
                    <a href="#!" class="btn btn-soft-primary w-100">Subscribe Now</a>                                        
                </div>
            </div>    
        </div>
    </div>
</div>
