// __Coral_v1.2.0/Gatsby/src/components/client/client-two.jsx
import React, { useEffect, useState } from 'react';
import { clientData } from '../../data/data'

import 'tiny-slider/dist/tiny-slider.css';

const settings = {
    controls: false,
    mouseDrag: true,
    loop: true,
    rewind: true,
    autoplay: true,
    autoplayButtonOutput: false,
    autoplayTimeout: 3000,
    navPosition: "bottom",
    speed: 400,
    gutter: 12,
    responsive: {
        992: {
            items: 3
        },

        767: {
            items: 2
        },

        320: {
            items: 1
        },
    },
};

export default function ClientTwo() {
    const [TinySlider, setTinySlider] = useState(null);
    
    useEffect(() => {
        import('tiny-slider-react').then((module) => {
            setTinySlider(() => module.default); 
        });
    }, []);
     if (!TinySlider) return null;
  return (
    <div className="tiny-three-item">
        <TinySlider settings={settings}>
            {clientData.map((item,index)=>( 
                <div className="tiny-slide" key={index}>
                    <div className="position-relative overflow-hidden z-1 bg-white rounded shadow p-4 m-2">
                        <div className="d-flex align-items-center justify-content-between">
                            <h6 className="mb-0">{item.tag}</h6>

                            <ul className="list-unstyled mb-0 text-warning">
                                {item.rate.map((el,index)=>( 
                                    <li className="list-inline-item" key={index}><i className={el}></i></li>
                                ))}
                            </ul>
                        </div>

                        <p className="text-muted fst-italic mt-2">{item.desc}</p>

                        <div className="d-flex align-items-center">
                            <img src={item.image} className="avatar avatar-small rounded-pill shadow" alt=""/>
                            <div className="ms-2">
                                <h6 className="text-dark small mb-0">{item.name}</h6>
                                <small className="text-muted d-block">{item.position}</small>
                            </div>
                        </div>
                        <i className="mdi mdi-format-quote-open text-primary position-absolute top-50 start-50 translate-middle z-n1 testi-icon"></i>
                    </div>
                </div>
            ))}
        </TinySlider>
    </div>
  )
}

// src/components/client/client-two.vue
<template>
    <div class="row">
        <div class="col-12 mt-4">
            <div class="tiny-three-item">
                <div v-for="(item, index) in clientData" :key="index" class="tiny-slide">
                    <div class="position-relative overflow-hidden z-1 bg-white rounded shadow p-4 m-2">
                        <div class="d-flex align-items-center justify-content-between">
                            <h6 class="mb-0">{{item.tag}}</h6>

                            <ul class="list-unstyled mb-0 text-warning">
                                <li v-for="(el, index) in item.rate" :key="index" class="list-inline-item"><i :class="el"></i></li>
                            </ul>
                        </div>

                        <p class="text-muted fst-italic mt-2">{{item.desc}}</p>

                        <div class="d-flex align-items-center">
                            <img :src="item.image" class="avatar avatar-small rounded-pill shadow" alt="">
                            <div class="ms-2">
                                <h6 class="text-dark small mb-0">{{item.name}}</h6>
                                <small class="text-muted d-block">{{item.position}}</small>
                            </div>
                        </div>

                        <i class="mdi mdi-format-quote-open text-primary position-absolute top-50 start-50 translate-middle z-n1 testi-icon"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script setup>
    import { clientData } from '@/data/data';
    import { onMounted } from 'vue';
    import { tns } from 'tiny-slider/src/tiny-slider';

    onMounted(()=>{
        tns({
            container: '.tiny-three-item',
            controls: false,
            mouseDrag: true,
            loop: true,
            rewind: true,
            autoplay: true,
            autoplayButtonOutput: false,
            autoplayTimeout: 3000,
            navPosition: "bottom",
            speed: 400,
            gutter: 12,
            nav:false,
            responsive: {
                992: {
                    items: 3
                },

                767: {
                    items: 2
                },

                320: {
                    items: 1
                },
            },
        });
    })


</script>
