// __Coral_v1.2.0/React/Javascript/src/pages/index/index-charity.jsx
import { Link } from 'react-router-dom'

import about1 from '../../assets/images/about/charity1.jpg'
import about2 from '../../assets/images/about/charity2.jpg'

import CountUp from 'react-countup'

import Navlight from '../../components/navbar/navlight'
import CharityBanner from '../../components/cta/charity-banner'
import CtaThree from '../../components/cta/cta-three'
import BlogOne from '../../components/blog/blog-one'
import TeamOne from '../../components/team/team-one'
import CharityServices from '../../components/services/charity-services'
import Footer from '../../components/footer'
import ScrollToTop from '../../components/scroll-to-top'

import { causeData } from '../../data/data'

export default function IndexCharity() {
  return (
    <>
        <Navlight/>

        <CharityBanner/>

        <section className="section">
            <div className="container">
                <div className="row">
                    <div className="col-lg-4 col-md-6 order-1 order-md-2">
                        <div className="features-absolute">
                            <div className="p-4 rounded shadow position-relative bg-white">
                                <div className="section-title">
                                    <h4 className="title mb-3">Make a Donation</h4>
                                    <p className="mb-0 text-muted">Your $40.00 monthly donation can give 12 people clean water every year. 100% funds water projects.</p>
                                </div>
    
                                <form className="mt-4">
                                    <div className="row">
                                        <div className="col-12">
                                            <div className="mb-3">
                                                <label className="form-label fw-semibold" htmlFor="name">Your Name : </label>
                                                <input name="name" id="name" type="text" className="form-control" placeholder="Your Name :"/>
                                            </div>
                                        </div>                               
        
                                        <div className="col-md-6 col-12">
                                            <div className="mb-3">
                                                <label className="form-label fw-semibold" htmlFor="email"> Your Mail : </label>
                                                <input name="email" id="email" type="email" className="form-control" placeholder="Your Mail :"/>
                                            </div> 
                                        </div>  
        
                                        <div className="col-md-6 col-12">
                                            <div className="mb-3">
                                                <label className="form-label fw-semibold" htmlFor="number2">Phone No. : </label>
                                                <input name="number" type="number" className="form-control" id="number2" placeholder="Phone :"/>
                                            </div> 
                                        </div> 
        
                                        <div className="col-12">
                                            <div className="mb-3">
                                                <label className="form-label fw-semibold">I Want to Donate for</label>
                                                <select className="form-select form-control" name="item_name">
                                                    <option value="Donate For Food">Donate For Food</option>
                                                    <option value="Food For Orphan">Food For Orphan</option>
                                                    <option value="Home For Homeless">Home For Homeless</option>
                                                    <option value="Holyday Gifts In Kind">Holyday Gifts In Kind</option>
                                                    <option value="For clean Water in Africa">For clean Water in Africa</option>
                                                    <option value="Health and Rights">Health and Rights</option>
                                                </select>
                                            </div>
                                        </div>
        
                                        <div className="col-12">
                                            <label className="form-label fw-semibold">How much do you want to donate ?</label>
                                            <div className="mb-3">
                                                <div className="input-group mb-3">
                                                    <span className="input-group-text" id="basic-addon1">$</span>
                                                    <input type="number" className="form-control" min="1" max="1000" placeholder="Enter Amount" id="amount" aria-describedby="inputGroupPrepend" required/>
                                                </div>
                                            </div>
                                        </div>                                                                          
        
                                        <div className="col-12">
                                            <div className="form-check">
                                                <input className="form-check-input" type="checkbox" value="" id="flexCheckDefault"/>
                                                <label className="form-check-label" htmlFor="flexCheckDefault">I agree to the <Link to="#" className="text-primary">Terms and Conditions</Link>.</label>
                                            </div>
                                        </div>                                    
        
                                        <div className="col-12 mt-3">
                                            <button type="submit" id="donatefund" name="send" className="btn btn-primary">Donate Us</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>

                    <div className="col-lg-8 col-md-6 order-2 order-md-1">
                        <div className="row align-items-center g-4">
                            <div className="col-lg-6 col-md-12">
                                <div className="position-relative">
                                    <div className="me-4">
                                        <img src={about1} className="img-fluid rounded shadow" alt=""/>
                                    </div>
                                    
                                    <div className="position-absolute end-0 top-50">
                                        <div className="position-relative overflow-hidden rounded shadow">
                                            <img src={about2} className="img-fluid avatar avatar-xl-large" alt=""/>
                                            <div className="bg-overlay bg-primary opacity-75"></div>

                                            <div className="position-absolute top-50 start-50 translate-middle">
                                                <div className="counter-box text-center">
                                                    <h2 className="fw-bold mb-0 text-white"><CountUp end={100}/>M</h2>
                                                    <p className="counter-head small fw-semibold text-white mb-0">PEOPLE FACING FOOD INSECURITY</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
        
                            <div className="col-lg-6 col-md-12">
                                <div className="section-title">
                                    <h6 className="fw-normal text-primary">ABOUT US</h6>
                                    <h4 className="title mb-4">The origin of <br/> the Fundraiser</h4>
        
                                    <p className="text-muted mb-0">Get instant helpful resources about anything on the go, easily implement secure money transfer solutions, boost your daily efficiency, connect to other app users and create your own Fronter network, and much more with just a few taps. commodo consequat. Duis aute irure.</p>
                                
                                    <div className="mt-4">
                                        <Link to="#" className="btn btn-primary">Read More <i className="mdi mdi-arrow-right"></i></Link>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div className="container mt-100 mt-60">
                <div className="row justify-content-center">
                    <div className="col-12">
                        <div className="section-title text-center mb-4 pb-2">
                            <h4 className="title mb-3">Popular Causes</h4>
                            <p className="text-muted para-desc mx-auto mb-0">The Coral is a non profit organisation that strives to eliminate hunger by implementing the Mid Day Meal Programme.</p>
                        </div>
                    </div>
                </div>

                <div className="row g-4">
                    {causeData.map((item,index)=>( 
                        <div className="col-lg-4 col-md-6" key={index}>
                            <div className="position-relative rounded bg-white shadow overflow-hidden">
                                <div className="position-relative overflow-hidden">
                                    <img src={item.image} className="img-fluid" alt=""/>
                                    <div className="bg-overlay bg-linear-gradient-2"></div>
                                    <div className="position-absolute bottom-0 p-4">
                                        <Link to="#" className="text-white title-dark fw-semibold link-title">Donate Now <i className="mdi mdi-arrow-right"></i></Link>
                                    </div>
                                </div>

                                <div className="content p-4">
                                    <h5><Link to="#" className="text-dark link-title">{item.title}</Link></h5>
                                    <p className="text-muted mb-0">{item.desc}</p>
                                    <div className="progress-box mt-5">
                                        <div className="progress rounded" style={{height: '8px'}}>
                                            <div className="progress-bar position-relative bg-primary rounded" style={{width:'60%'}}>
                                                <div className="progress-value d-block text-dark h6 mb-0">{item.progress}</div>
                                            </div>
                                        </div>
                                    </div>

                                    <div className="d-flex align-items-center justify-content-between mt-3">
                                        <h6 className="text-muted mb-0">{item.value1}</h6>
                                        <h6 className="text-muted mb-0">{item.value2}</h6>
                                    </div>
                                </div>
                            </div>
                        </div>
                    ))}
                </div>
            </div>
        </section>

        <CtaThree/>

         <section className="section">
            <div className="container">
                <div className="row justify-content-center">
                    <div className="col-12">
                        <div className="section-title text-center mb-4 pb-2">
                            <h4 className="title mb-3">We Have Funded <span className="text-primary">150 Charity Projects</span> for <br/> 10M People Around The World.</h4>
                            <p className="text-muted para-desc mx-auto mb-0">The Coral is a non profit organisation that strives to eliminate hunger by implementing the Mid Day Meal Programme.</p>
                        </div>
                    </div>
                </div>
                <CharityServices/>
            </div>

            <div className="container mt-100 mt-60">
                <div className="row justify-content-center">
                    <div className="col-12">
                        <div className="section-title text-center mb-4 pb-2">
                            <h4 className="title mb-3">Our Volunteers</h4>
                            <p className="text-muted para-desc mx-auto mb-0">The Coral is a non profit organisation that strives to eliminate hunger by implementing the Mid Day Meal Programme.</p>
                        </div>
                    </div>
                </div>
                <TeamOne/>
            </div>

            <div className="container mt-100 mt-60">
                <div className="row justify-content-center">
                    <div className="col-12">
                        <div className="section-title text-center mb-4 pb-2">
                            <h4 className="title mb-3">Blog Or News</h4>
                            <p className="text-muted para-desc mx-auto mb-0">The Coral is a non profit organisation that strives to eliminate hunger by implementing the Mid Day Meal Programme.</p>
                        </div>
                    </div>
                </div>
                <BlogOne/>
            </div>
        </section>

        <Footer/>

        <ScrollToTop/>
    </>
  )
}

// src/pages/index/index-charity.vue
<template>
    <div>
        <NavLight/>

        <section class="bg-half-260" id="home" :style="{backgroundImage:`url(${randomImage})`, backgroundPosition:'center'}">
            <div class="bg-overlay bg-gradient-overlay"></div>
            <div class="container">
                <div class="row align-items-center mt-5">
                    <div class="col-lg-7 col-md-8 order-md-1 order-2">
                        <div class="title-heading">
                            <h1 class="heading text-white title-dark fw-bold mb-4 text-capitalize">Give a Helping Hand <br> for Children</h1>
                            <p class="para-desc text-white-50">We value every human life placed in our hands and constantly work towards meeting the expectations of our patients.</p>

                            <div class="mt-4 pt-2">
                                <router-link to="#" class="btn btn-primary me-1">Enroll Today</router-link>
                                <router-link to="#" class="btn btn-soft-primary">Make a Donation</router-link>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-5 col-md-4 order-md-2 order-1">
                        <div class="d-md-flex justify-content-center">
                            <a href="#!" data-bs-toggle="modal" data-bs-target="#staticBackdrop" class="avatar avatar-md-md rounded-pill shadow bg-white d-flex justify-content-center align-items-center lightbox">
                                <i class="mdi mdi-play mdi-24px text-primary"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <section class="section">
            <div class="container">
                <div class="row">
                    <div class="col-lg-4 col-md-6 order-1 order-md-2">
                        <div class="features-absolute">
                            <div class="p-4 rounded shadow position-relative bg-white">
                                <div class="section-title">
                                    <h4 class="title mb-3">Make a Donation</h4>
                                    <p class="mb-0 text-muted">Your $40.00 monthly donation can give 12 people clean water every year. 100% funds water projects.</p>
                                </div>
    
                                <form class="mt-4">
                                    <div class="row">
                                        <div class="col-12">
                                            <div class="mb-3">
                                                <label class="form-label fw-semibold" for="name">Your Name : </label>
                                                <input name="name" id="name" type="text" class="form-control" placeholder="Your Name :">
                                            </div>
                                        </div>                               
        
                                        <div class="col-md-6 col-12">
                                            <div class="mb-3">
                                                <label class="form-label fw-semibold" for="email"> Your Mail : </label>
                                                <input name="email" id="email" type="email" class="form-control" placeholder="Your Mail :">
                                            </div> 
                                        </div>  
        
                                        <div class="col-md-6 col-12">
                                            <div class="mb-3">
                                                <label class="form-label fw-semibold" for="number2">Phone No. : </label>
                                                <input name="number" type="number" class="form-control" id="number2" placeholder="Phone :">
                                            </div> 
                                        </div> 
        
                                        <div class="col-12">
                                            <div class="mb-3">
                                                <label class="form-label fw-semibold">I Want to Donate for</label>
                                                <select class="form-select form-control" name="item_name">
                                                    <option value="Donate For Food">Donate For Food</option>
                                                    <option value="Food For Orphan">Food For Orphan</option>
                                                    <option value="Home For Homeless">Home For Homeless</option>
                                                    <option value="Holyday Gifts In Kind">Holyday Gifts In Kind</option>
                                                    <option value="For clean Water in Africa">For clean Water in Africa</option>
                                                    <option value="Health and Rights">Health and Rights</option>
                                                </select>
                                            </div>
                                        </div>
        
                                        <div class="col-12">
                                            <label class="form-label fw-semibold">How much do you want to donate ?</label>
                                            <div class="mb-3">
                                                <div class="input-group mb-3">
                                                    <span class="input-group-text" id="basic-addon1">$</span>
                                                    <input type="number" class="form-control" min="1" max="1000" placeholder="Enter Amount" id="amount" aria-describedby="inputGroupPrepend" required>
                                                </div>
                                            </div>
                                        </div>                                                                          
        
                                        <div class="col-12">
                                            <div class="form-check">
                                                <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
                                                <label class="form-check-label" for="flexCheckDefault">I agree to the <a href="javascript:void(0)" class="text-primary">Terms and Conditions</a>.</label>
                                            </div>
                                        </div>                                    
        
                                        <div class="col-12 mt-3">
                                            <button type="submit" id="donatefund" name="send" class="btn btn-primary">Donate Us</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-8 col-md-6 order-2 order-md-1">
                        <div class="row align-items-center g-4">
                            <div class="col-lg-6 col-md-12">
                                <div class="position-relative">
                                    <div class="me-4">
                                        <img :src="about1" class="img-fluid rounded shadow" alt="">
                                    </div>
                                    
                                    <div class="position-absolute end-0 top-50">
                                        <div class="position-relative overflow-hidden rounded shadow">
                                            <img :src="about2" class="img-fluid avatar avatar-xl-large" alt="">
                                            <div class="bg-overlay bg-primary opacity-75"></div>

                                            <div class="position-absolute top-50 start-50 translate-middle">
                                                <div class="counter-box text-center">
                                                    <h2 class="fw-bold mb-0 text-white"><span class="counter-value" data-target="100">100</span>M</h2>
                                                    <p class="counter-head small fw-semibold text-white mb-0">PEOPLE FACING FOOD INSECURITY</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
        
                            <div class="col-lg-6 col-md-12">
                                <div class="section-title">
                                    <h6 class="fw-normal text-primary">ABOUT US</h6>
                                    <h4 class="title mb-4">The origin of <br> the Fundraiser</h4>
        
                                    <p class="text-muted mb-0">Get instant helpful resources about anything on the go, easily implement secure money transfer solutions, boost your daily efficiency, connect to other app users and create your own Fronter network, and much more with just a few taps. commodo consequat. Duis aute irure.</p>
                                
                                    <div class="mt-4">
                                        <router-link to="#" class="btn btn-primary">Read More <i class="mdi mdi-arrow-right"></i></router-link>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="container mt-100 mt-60">
                <div class="row justify-content-center">
                    <div class="col-12">
                        <div class="section-title text-center mb-4 pb-2">
                            <h4 class="title mb-3">Popular Causes</h4>
                            <p class="text-muted para-desc mx-auto mb-0">The Coral is a non profit organisation that strives to eliminate hunger by implementing the Mid Day Meal Programme.</p>
                        </div>
                    </div>
                </div>

                <div class="row g-4">
                    <div v-for="(item, index) in causeData" :key="index" class="col-lg-4 col-md-6">
                        <div class="position-relative rounded bg-white shadow overflow-hidden">
                            <div class="position-relative overflow-hidden">
                                <img :src="item.image" class="img-fluid" alt="">
                                <div class="bg-overlay bg-linear-gradient-2"></div>
                                <div class="position-absolute bottom-0 p-4">
                                    <router-link to="#" class="text-white title-dark fw-semibold link-title">Donate Now <i class="mdi mdi-arrow-right"></i></router-link>
                                </div>
                            </div>

                            <div class="content p-4">
                                <h5><router-link to="#" class="text-dark link-title">{{item.title}}</router-link></h5>
                                <p class="text-muted mb-0">{{item.desc}}</p>
                                <div class="progress-box mt-5">
                                    <div class="progress rounded" style="height: 8px;">
                                        <div class="progress-bar position-relative bg-primary rounded" style="width:60%;">
                                            <div class="progress-value d-block text-dark h6 mb-0">{{item.progress}}</div>
                                        </div>
                                    </div>
                                </div>

                                <div class="d-flex align-items-center justify-content-between mt-3">
                                    <h6 class="text-muted mb-0">{{item.value1}}</h6>
                                    <h6 class="text-muted mb-0">{{item.value2}}</h6>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <CtaTwo/>

        <section class="section">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-12">
                        <div class="section-title text-center mb-4 pb-2">
                            <h4 class="title mb-3">We Have Funded <span class="text-primary">150 Charity Projects</span> for <br> 10M People Around The World.</h4>
                            <p class="text-muted para-desc mx-auto mb-0">The Coral is a non profit organisation that strives to eliminate hunger by implementing the Mid Day Meal Programme.</p>
                        </div>
                    </div>
                </div>
                <ServicesTwo/>
            </div>

            <div class="container mt-100 mt-60">
                <div class="row justify-content-center">
                    <div class="col-12">
                        <div class="section-title text-center mb-4 pb-2">
                            <h4 class="title mb-3">Our Volunteers</h4>
                            <p class="text-muted para-desc mx-auto mb-0">The Coral is a non profit organisation that strives to eliminate hunger by implementing the Mid Day Meal Programme.</p>
                        </div>
                    </div>
                </div>
                <TeamOne/>
            </div>

            <div class="container mt-100 mt-60">
                <div class="row justify-content-center">
                    <div class="col-12">
                        <div class="section-title text-center mb-4 pb-2">
                            <h4 class="title mb-3">Blog Or News</h4>
                            <p class="text-muted para-desc mx-auto mb-0">The Coral is a non profit organisation that strives to eliminate hunger by implementing the Mid Day Meal Programme.</p>
                        </div>
                    </div>
                </div>
                <BlogOne/>
            </div>
        </section>

        <FooterOne/>
        
        <ScrollToTop/>
    </div>
</template>

<script setup>
    import { onMounted, ref } from 'vue';
    import NavLight from '@/components/navbar/nav-light.vue';
    import bg1 from '@/assets/images/hero/charity1.jpg'
    import bg2 from '@/assets/images/hero/charity2.jpg'
    import bg3 from '@/assets/images/hero/charity3.jpg'
    import about1 from '@/assets/images/about/charity1.jpg'
    import about2 from '@/assets/images/about/charity2.jpg'
import { causeData } from '@/data/data';
import CtaTwo from '@/components/cta/cta-two.vue';
import ServicesTwo from '@/components/services/services-two.vue';
import TeamOne from '@/components/team/team-one.vue';
import BlogOne from '@/components/blog/blog-one.vue';
import FooterOne from '@/components/footer-one.vue';
import ScrollToTop from '@/components/scroll-to-top.vue';

    const randomImage = ref('')

    const backgroundImages = ref([bg1,bg2,bg3])

    const changeBackground = () =>{
        const randomIndex = Math.floor(Math.random() * backgroundImages.value.length);
        randomImage.value = backgroundImages.value[randomIndex];
    }

    onMounted(() => {
        changeBackground();
        setInterval(changeBackground, 5000);
    })

</script>
