// __Coral_v1.2.0/Svelte/src/pages/index/index-finance.svelte
<script>
// @ts-nocheck

    import bg1 from '../../assets/images/hero/bg1.jpg'
    import bg2 from '../../assets/images/hero/bg2.jpg'
    import bg3 from '../../assets/images/hero/bg3.jpg'
    import about1 from '../../assets/images/1.jpg'
    import about2 from '../../assets/images/2.jpg'
    import about3 from '../../assets/images/3.jpg'
    import { onMount } from "svelte";
    import NavBg from "../../components/navbar/nav-bg.svelte";
    import { servicesData } from '../../data/data';
    import { Link } from 'svelte-routing';
    import CtaTwo from '../../components/cta/cta-two.svelte';
    import BlogOne from '../../components/blog-one.svelte';
    import FaqOne from '../../components/faq-one.svelte';
    import Footer from '../../components/footer.svelte';

    import Tobii from 'tobii';

    let tobii;

    let randomImage ;
    let backgroundImages =[bg1,bg2,bg3]

    const changeBackground = () =>{
        const randomIndex = Math.floor(Math.random() * backgroundImages.length);
        randomImage = backgroundImages[randomIndex];
    }

    onMount(()=>{
        tobii = new Tobii();
        changeBackground();
        setInterval(changeBackground, 5000);
    })

</script>

<NavBg/>

<section class="d-flex align-items-center bg-finance" style="background: url('{randomImage}') center;" id="home">
    <div class="container position-relative z-1">
        <div class="row">
            <div class="col-md-6 background">
                <div class="title-heading pe-lg-5 pe-md-4">
                    <span class="badge bg-primary mb-2">Coral Finance</span>
                    <h1 class="heading fw-semibold text-capitalize mb-3">Maximize your <br> <span class="border-animation position-relative">income and build</span> lasting wealth.</h1>
                    <p class="para-desc text-muted mb-0">Ensuring secure transactions and seamless financial experiences for our users globally.</p>
                
                    <div class="mt-4">
                        <a href="#!" class="btn btn-primary me-1">Get Started <i class="mdi mdi-arrow-right"></i></a>
                        <a href="#!" class="btn btn-outline-primary">Learn More</a>
                    </div>

                    <ul class="list-unstyled mt-3 text-muted mb-0">
                        <li class="list-inline-item me-4"><i class="mdi mdi-check text-primary me-2"></i>Hire experts</li>
                        <li class="list-inline-item me-4"><i class="mdi mdi-check text-primary me-2"></i>Avoid scams</li>
                        <li class="list-inline-item me-4"><i class="mdi mdi-check text-primary me-2"></i>Contingecy fees</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="bg-white py-5 border-top border-bottom">
    <div class="container">
        <div class="row align-items-center g-4">
            {#each servicesData.slice(0,4) as item}
                <div class="col-lg-3 col-md-6">
                    <div class="card rounded p-4 py-5 bg-primary position-relative overflow-hidden border-0">
                        <i data-feather={item.icon} class="fea icon-md text-white z-1"></i>
                        <div class="card-body p-0 mt-4">
                            <h5 class="text-white">{item.title}</h5>
                            <p class="para text-white-50 mb-0">{item.desc}</p>
                        </div>
                    </div>
                </div>
            {/each}
        </div>
    </div>
</section>

<section class="section">
    <div class="container">
        <div class="row align-items-center g-4">
            <div class="col-lg-5 col-md-6">
                <div class="rounded shadow bg-soft-primary p-4 pb-0">
                    <img src={about1} class="img-fluid rounded-top shadow" alt="">
                </div>
            </div>

            <div class="col-lg-7 col-md-6">
                <div class="section-title ms-lg-5">
                    <h4 class="title mb-3">Gain valuable insights. <br> Fast data analytics</h4>
                    <p class="text-muted para-desc mb-0">Ensuring secure transactions and seamless financial experiences for our users globally.</p>
                
                    <ul class="list-unstyled text-muted mb-0 mt-3">
                        <li class="mb-1"><span class="text-primary h5 me-2"><i class="mdi mdi-check-circle-outline align-middle"></i></span>Digital Marketing Solutions for Tomorrow</li>
                        <li class="mb-1"><span class="text-primary h5 me-2"><i class="mdi mdi-check-circle-outline align-middle"></i></span>Our Talented & Experienced Marketing Agency</li>
                        <li class="mb-1"><span class="text-primary h5 me-2"><i class="mdi mdi-check-circle-outline align-middle"></i></span>Create your own skin to match your brand</li>
                    </ul>

                    <div class="mt-4">
                        <Link to="/aboutus" class="btn btn-soft-primary">About Us <i class="mdi mdi-arrow-right align-middle"></i></Link>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container mt-100 mt-60">
        <div class="row align-items-center g-4">
            <div class="col-lg-5 col-md-6 order-1 order-md-2">
                <div class="rounded shadow bg-soft-primary p-4 pb-0">
                    <img src={about2} class="img-fluid rounded-top shadow" alt="">
                </div>
            </div>

            <div class="col-lg-7 col-md-6 order-md-1 order-2">
                <div class="section-title me-lg-5">
                    <h4 class="title mb-3">Review and manage <br> team salaries</h4>
                    <p class="text-muted para-desc mb-0">Ensuring secure transactions and seamless financial experiences for our users globally.</p>
                
                    <ul class="list-unstyled text-muted mb-0 mt-3">
                        <li class="mb-1"><span class="text-primary h5 me-2"><i class="mdi mdi-check-circle-outline align-middle"></i></span>Digital Marketing Solutions for Tomorrow</li>
                        <li class="mb-1"><span class="text-primary h5 me-2"><i class="mdi mdi-check-circle-outline align-middle"></i></span>Our Talented & Experienced Marketing Agency</li>
                        <li class="mb-1"><span class="text-primary h5 me-2"><i class="mdi mdi-check-circle-outline align-middle"></i></span>Create your own skin to match your brand</li>
                    </ul>

                    <div class="mt-4">
                        <Link to="/aboutus" class="btn btn-soft-primary">About Us <i class="mdi mdi-arrow-right align-middle"></i></Link>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container mt-100 mt-60">
        <div class="row align-items-center g-4">
            <div class="col-lg-5 col-md-6">
                <div class="rounded shadow bg-soft-primary p-4 pb-0">
                    <img src={about3} class="img-fluid rounded-top shadow" alt="">
                </div>
            </div>

            <div class="col-lg-7 col-md-6">
                <div class="section-title ms-lg-5">
                    <h4 class="title mb-3">In-depth financial <br> performance analysis</h4>
                    <p class="text-muted para-desc mb-0">Ensuring secure transactions and seamless financial experiences for our users globally.</p>
                
                    <ul class="list-unstyled text-muted mb-0 mt-3">
                        <li class="mb-1"><span class="text-primary h5 me-2"><i class="mdi mdi-check-circle-outline align-middle"></i></span>Digital Marketing Solutions for Tomorrow</li>
                        <li class="mb-1"><span class="text-primary h5 me-2"><i class="mdi mdi-check-circle-outline align-middle"></i></span>Our Talented & Experienced Marketing Agency</li>
                        <li class="mb-1"><span class="text-primary h5 me-2"><i class="mdi mdi-check-circle-outline align-middle"></i></span>Create your own skin to match your brand</li>
                    </ul>

                    <div class="mt-4">
                        <Link to="/aboutus" class="btn btn-soft-primary">About Us <i class="mdi mdi-arrow-right align-middle"></i></Link>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<CtaTwo/>

<section class="section">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6 col-md-6">
                <div class="section-title mb-md-0 mb-0 ms-lg-3">
                    <span class="badge bg-primary mb-2">FAQs</span>
                    <h4 class="title mb-3 mb-md-5 pb-md-4">Got a question? <br> Get your answer</h4>
                    <p class="text-muted para-desc mb-0 mt-md-4">Ensuring secure transactions and seamless financial experiences for our users globally.</p>
                    <div class="mt-3 d-none d-md-block">
                        <a href="#!" class="btn btn-soft-primary">Contact Now <i class="mdi mdi-arrow-right"></i></a>
                    </div>
                </div>
            </div>

            <div class="col-lg-6 col-md-6 mt-4 mt-md-0 pt-2 pt-md-0">
                <div class="ms-lg-3">                        
                    <FaqOne/>
                </div>
            </div>
        </div>
    </div>

    <div class="container mt-100 mt-60">
        <div class="row justify-content-center">
            <div class="col-12">
                <div class="section-title text-center mb-4 pb-2">
                    <h4 class="title mb-3">Blog Or News</h4>
                    <p class="text-muted para-desc mx-auto mb-0">Ensuring secure transactions and seamless financial experiences for our users globally.</p>
                </div>
            </div>
        </div>
        <BlogOne/>
    </div>
</section>

<Footer/>

// src/pages/index/index-finance.vue
<template>
    <div>
        <NavDark bg="bg-white" tagline="" position="nav-right"/>

        <section class="d-flex align-items-center bg-finance" id="home" :style="{backgroundImage:`url(${randomImage})`}">
            <div class="container position-relative z-1">
                <div class="row">
                    <div class="col-md-6 background">
                        <div class="title-heading pe-lg-5 pe-md-4">
                            <span class="badge bg-primary mb-2">Coral Finance</span>
                            <h1 class="heading fw-semibold text-capitalize mb-3">Maximize your <br> <span class="border-animation position-relative">income and build</span> lasting wealth.</h1>
                            <p class="para-desc text-muted mb-0">Ensuring secure transactions and seamless financial experiences for our users globally.</p>
                        
                            <div>
                                <router-link to="#" class="btn btn-primary me-1 mt-4">Get Started <i class="mdi mdi-arrow-right"></i></router-link>
                                <router-link to="#" class="btn btn-outline-primary mt-4">Learn More</router-link>
                            </div>

                            <ul class="list-unstyled mt-3 text-muted mb-0">
                                <li class="list-inline-item me-4"><i class="mdi mdi-check text-primary me-2"></i>Hire experts</li>
                                <li class="list-inline-item me-4"><i class="mdi mdi-check text-primary me-2"></i>Avoid scams</li>
                                <li class="list-inline-item me-4"><i class="mdi mdi-check text-primary me-2"></i>Contingecy fees</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <section class="bg-white py-5 border-top border-bottom">
            <div class="container">
                <div class="row align-items-center g-4">
                    <div v-for="(item, index) in servicesData.slice(0,4)" :key="index" class="col-lg-3 col-md-6">
                        <div class="card rounded p-4 py-5 bg-primary position-relative overflow-hidden border-0">
                            <i :data-feather="item.icon" class="fea icon-md text-white z-1"></i>
                            <div class="card-body p-0 mt-4">
                                <h5 class="text-white">{{item.title}}</h5>
                                <p class="para text-white-50 mb-0">{{item.desc}}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <section class="section">
            <div class="container">
                <div class="row align-items-center g-4">
                    <div class="col-lg-5 col-md-6">
                        <div class="rounded shadow bg-soft-primary p-4 pb-0">
                            <img :src="about1" class="img-fluid rounded-top shadow" alt="">
                        </div>
                    </div>

                    <div class="col-lg-7 col-md-6">
                        <div class="section-title ms-lg-5">
                            <h4 class="title mb-3">Gain valuable insights. <br> Fast data analytics</h4>
                            <p class="text-muted para-desc mb-0">Ensuring secure transactions and seamless financial experiences for our users globally.</p>
                        
                            <ul class="list-unstyled text-muted mb-0 mt-3">
                                <li class="mb-1"><span class="text-primary h5 me-2"><i class="mdi mdi-check-circle-outline align-middle"></i></span>Digital Marketing Solutions for Tomorrow</li>
                                <li class="mb-1"><span class="text-primary h5 me-2"><i class="mdi mdi-check-circle-outline align-middle"></i></span>Our Talented & Experienced Marketing Agency</li>
                                <li class="mb-1"><span class="text-primary h5 me-2"><i class="mdi mdi-check-circle-outline align-middle"></i></span>Create your own skin to match your brand</li>
                            </ul>

                            <div class="mt-4">
                                <router-link to="/aboutus" class="btn btn-soft-primary">About Us <i class="mdi mdi-arrow-right align-middle"></i></router-link>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="container mt-100 mt-60">
                <div class="row align-items-center g-4">
                    <div class="col-lg-5 col-md-6 order-1 order-md-2">
                        <div class="rounded shadow bg-soft-primary p-4 pb-0">
                            <img :src="about2" class="img-fluid rounded-top shadow" alt="">
                        </div>
                    </div>

                    <div class="col-lg-7 col-md-6 order-md-1 order-2">
                        <div class="section-title me-lg-5">
                            <h4 class="title mb-3">Review and manage <br> team salaries</h4>
                            <p class="text-muted para-desc mb-0">Ensuring secure transactions and seamless financial experiences for our users globally.</p>
                        
                            <ul class="list-unstyled text-muted mb-0 mt-3">
                                <li class="mb-1"><span class="text-primary h5 me-2"><i class="mdi mdi-check-circle-outline align-middle"></i></span>Digital Marketing Solutions for Tomorrow</li>
                                <li class="mb-1"><span class="text-primary h5 me-2"><i class="mdi mdi-check-circle-outline align-middle"></i></span>Our Talented & Experienced Marketing Agency</li>
                                <li class="mb-1"><span class="text-primary h5 me-2"><i class="mdi mdi-check-circle-outline align-middle"></i></span>Create your own skin to match your brand</li>
                            </ul>

                            <div class="mt-4">
                                <router-link to="/aboutus" class="btn btn-soft-primary">About Us <i class="mdi mdi-arrow-right align-middle"></i></router-link>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="container mt-100 mt-60">
                <div class="row align-items-center g-4">
                    <div class="col-lg-5 col-md-6">
                        <div class="rounded shadow bg-soft-primary p-4 pb-0">
                            <img :src="about3" class="img-fluid rounded-top shadow" alt="">
                        </div>
                    </div>

                    <div class="col-lg-7 col-md-6">
                        <div class="section-title ms-lg-5">
                            <h4 class="title mb-3">In-depth financial <br> performance analysis</h4>
                            <p class="text-muted para-desc mb-0">Ensuring secure transactions and seamless financial experiences for our users globally.</p>
                        
                            <ul class="list-unstyled text-muted mb-0 mt-3">
                                <li class="mb-1"><span class="text-primary h5 me-2"><i class="mdi mdi-check-circle-outline align-middle"></i></span>Digital Marketing Solutions for Tomorrow</li>
                                <li class="mb-1"><span class="text-primary h5 me-2"><i class="mdi mdi-check-circle-outline align-middle"></i></span>Our Talented & Experienced Marketing Agency</li>
                                <li class="mb-1"><span class="text-primary h5 me-2"><i class="mdi mdi-check-circle-outline align-middle"></i></span>Create your own skin to match your brand</li>
                            </ul>

                            <div class="mt-4">
                                <router-link to="/aboutus" class="btn btn-soft-primary">About Us <i class="mdi mdi-arrow-right align-middle"></i></router-link>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <CtaTwo/>

        <section class="section">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-6 col-md-6">
                        <div class="section-title mb-md-0 mb-0 ms-lg-3">
                            <span class="badge bg-primary mb-2">FAQs</span>
                            <h4 class="title mb-3 mb-md-5 pb-md-4">Got a question? <br> Get your answer</h4>
                            <p class="text-muted para-desc mb-0 mt-md-4">Ensuring secure transactions and seamless financial experiences for our users globally.</p>
                            <div class="mt-3 d-none d-md-block">
                                <router-link to="#" class="btn btn-soft-primary">Contact Now <i class="mdi mdi-arrow-right"></i></router-link>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-6 col-md-6 mt-4 mt-md-0 pt-2 pt-md-0">
                        <div class="ms-lg-3">                        
                            <FaqOne/>
                        </div>
                    </div>
                </div>
            </div>

            <div class="container mt-100 mt-60">
                <div class="row justify-content-center">
                    <div class="col-12">
                        <div class="section-title text-center mb-4 pb-2">
                            <h4 class="title mb-3">Blog Or News</h4>
                            <p class="text-muted para-desc mx-auto mb-0">Ensuring secure transactions and seamless financial experiences for our users globally.</p>
                        </div>
                    </div>
                </div>
                <BlogOne/>
            </div>
        </section>

        <FooterOne/>

        <ScrollToTop/>

    </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'

import about1 from '@/assets/images/1.jpg'
import about2 from '@/assets/images/2.jpg'
import about3 from '@/assets/images/3.jpg'
import bg1 from '@/assets/images/hero/bg1.jpg'
import bg2 from '@/assets/images/hero/bg2.jpg'
import bg3 from '@/assets/images/hero/bg3.jpg'

import NavDark from '@/components/navbar/nav-dark.vue';
import CtaTwo from '@/components/cta/cta-two.vue';
import BlogOne from '@/components/blog/blog-one.vue';
import FaqOne from '@/components/faq-one.vue';

import { servicesData } from '@/data/data';
import FooterOne from '@/components/footer-one.vue'
import ScrollToTop from '@/components/scroll-to-top.vue'

const randomImage = ref('')
const backgroundImages = ref([bg1,bg2,bg3])

const changeBackground = () =>{
    const randomIndex = Math.floor(Math.random() * backgroundImages.value.length);
    randomImage.value = backgroundImages.value[randomIndex];
}

onMounted(() => {
    changeBackground();
    setInterval(changeBackground, 5000);
})


</script>
