// __Coral_v1.2.0/React/Javascript/src/pages/inner-pages/testimonial.jsx
import { Link } from 'react-router-dom'
import bg from '../../assets/images/hero/pages.jpg'

import { clientData } from '../../data/data'

import Navlight from '../../components/navbar/navlight'
import Footer from '../../components/footer'
import ScrollToTop from '../../components/scroll-to-top'

export default function Testimonial() {
  return (
    <>
        <Navlight/>

        <section className="bg-half-170 d-table w-100" style={{backgroundImage:`url(${bg})`, backgroundPosition:'center'}}>
            <div className="bg-overlay bg-gradient-overlay"></div>
            <div className="container">
                <div className="row mt-5 justify-content-center">
                    <div className="col-12">
                        <div className="title-heading text-center">
                            <h5 className="heading fw-semibold mb-0 sub-heading text-white title-dark">Testimonial</h5>
                        </div>
                    </div>
                </div>

                <div className="position-middle-bottom">
                    <nav aria-label="breadcrumb" className="d-block">
                        <ul className="breadcrumb breadcrumb-muted mb-0 p-0">
                            <li className="breadcrumb-item"><Link to="/">Coral</Link></li>
                            <li className="breadcrumb-item active" aria-current="page">Testimonial</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </section>

        <div className="position-relative">
            <div className="shape overflow-hidden text-white">
                <svg viewBox="0 0 2880 48" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M0 48H1437.5H2880V0H2160C1442.5 52 720 0 720 0H0V48Z" fill="currentColor"></path>
                </svg>
            </div>
        </div>   

        <section className="section">
            <div className="container">
                <div className="column-3">
                    {clientData.map((item,index)=>{
                        return(
                            <div className="mb-3" key={index}>
                                <div className="position-relative overflow-hidden z-1 bg-white rounded shadow p-4">
                                    <div className="d-flex align-items-center justify-content-between">
                                        <h6 className="mb-0">{item.tag}</h6>

                                        <ul className="list-unstyled mb-0 text-warning">
                                            {item.rate.map((el,index)=>(
                                                <li className="list-inline-item" key={index}><i className={el}></i></li>
                                            ))}
                                        </ul>
                                    </div>

                                    <p className="text-muted fst-italic mt-2">{item.desc}</p>

                                    <div className="d-flex align-items-center">
                                        <img src={item.image} className="avatar avatar-small rounded-pill shadow" alt=""/>
                                        <div className="ms-2">
                                            <h6 className="text-dark small mb-0">{item.name}</h6>
                                            <small className="text-muted d-block">{item.position}</small>
                                        </div>
                                    </div>

                                    <i className="mdi mdi-format-quote-open text-primary position-absolute top-50 start-50 translate-middle z-n1 testi-icon"></i>
                                </div>
                            </div>
                        )
                    })}
                </div>

                <div className="row justify-content-center">
                    <div className="col mt-4">
                        <div className="text-center">
                            <Link to="#" className="text-primary">See More <i className="mdi mdi-chevron-right"></i></Link>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <Footer/>

        <ScrollToTop/>
    </>
  )
}

// __Coral_v1.2.0/Svelte/src/pages/inner-pages/testimonial.svelte
<script>
    import { Link } from "svelte-routing";
    import bg from "../../assets/images/hero/pages.jpg";
    import Navlight from "../../components/navbar/navlight.svelte";
    import { clientData } from "../../data/data";
    import Footer from "../../components/footer.svelte";

</script>

<Navlight/>

<section class="bg-half-170 d-table w-100" style="background: url({bg}) center;">
    <div class="bg-overlay bg-gradient-overlay"></div>
    <div class="container">
        <div class="row mt-5 justify-content-center">
            <div class="col-12">
                <div class="title-heading text-center">
                    <h5 class="heading fw-semibold mb-0 sub-heading text-white title-dark">Testimonial</h5>
                </div>
            </div>
        </div>

        <div class="position-middle-bottom">
            <nav aria-label="breadcrumb" class="d-block">
                <ul class="breadcrumb breadcrumb-muted mb-0 p-0">
                    <li class="breadcrumb-item"><Link to="/">Coral</Link></li>
                    <li class="breadcrumb-item active" aria-current="page">Testimonial</li>
                </ul>
            </nav>
        </div>
    </div>
</section>

<div class="position-relative">
    <div class="shape overflow-hidden text-white">
        <svg viewBox="0 0 2880 48" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M0 48H1437.5H2880V0H2160C1442.5 52 720 0 720 0H0V48Z" fill="currentColor"></path>
        </svg>
    </div>
</div>

<section class="section">
    <div class="container">
        <div class="column-3 gap-4">
            {#each clientData as item}
                <div class="mb-4">
                    <div class="position-relative overflow-hidden z-1 bg-white rounded shadow p-4">
                        <div class="d-flex align-items-center justify-content-between">
                            <h6 class="mb-0">{item.tag}</h6>

                            <ul class="list-unstyled mb-0 text-warning">
                                {#each item.rate as el}
                                    <li class="list-inline-item"><i class={el}></i></li>
                                {/each}
                            </ul>
                        </div>

                        <p class="text-muted fst-italic mt-2">{item.desc}</p>

                        <div class="d-flex align-items-center">
                            <img src={item.image} class="avatar avatar-small rounded-pill shadow" alt="">
                            <div class="ms-2">
                                <h6 class="text-dark small mb-0">{item.name}</h6>
                                <small class="text-muted d-block">{item.position}</small>
                            </div>
                        </div>

                        <i class="mdi mdi-format-quote-open text-primary position-absolute top-50 start-50 translate-middle z-n1 testi-icon"></i>
                    </div>
                </div>
            {/each}
        </div>

        <div class="row justify-content-center">
            <div class="col mt-4">
                <div class="text-center">
                    <a href="#!" class="text-primary">See More <i class="mdi mdi-chevron-right"></i></a>
                </div>
            </div>
        </div>
    </div>
</section>

<Footer/>
