// __Coral_v1.2.0/Nuxt/app/components/project/project-two.vue
<template>
    <div class="row g-4">
        <div v-for="(item, index) in projectData" :key="index" class="col-lg-3 col-md-4">
            <div class="portfolio modern rounded shadow position-relative overflow-hidden">
                <div class="position-relative overflow-hidden image">
                    <img :src="item.image" class="img-fluid" alt="">
                </div>

                <div class="content p-3 bg-white position-absolute bottom-0 start-0 end-0 rounded m-4">
                    <NuxtLink to="#" class="text-dark fs-5 fw-medium link-title">{{item.title}}</NuxtLink>
                    <p class="text-muted mb-0">{{item.name}}</p>
                </div>
            </div>
        </div>
    </div>
</template>

<script setup>
import { projectData } from '@/data/data';
</script>

// __Coral_v1.2.0/Gatsby/src/components/portfolio/project-two.jsx
import React from 'react'
import { portfolioOne } from '../../data/data'
import { Link } from 'gatsby'

export default function ProjectTwo() {
  return (
    <div className="row g-4">
        {portfolioOne.map((item,index)=>( 
            <div className="col-lg-3 col-md-4 " key={index}>
                <div className="portfolio modern rounded shadow position-relative overflow-hidden">
                    <div className="position-relative overflow-hidden image">
                        <img src={item.image} className="img-fluid" alt=""/>
                    </div>

                    <div className="content p-3 bg-white position-absolute bottom-0 start-0 end-0 rounded m-4">
                        <Link to="#" className="text-dark fs-5 fw-medium link-title">{item.title}</Link>
                        <p className="text-muted mb-0">{item.name}</p>
                    </div>
                </div>
            </div>
        ))}
    </div>
  )
}
