// __Coral_v1.2.0/Nuxt/app/pages/reset-password.vue
<template>
    <section class="bg-home d-flex align-items-center" :style="{backgroundImage:`url(${bg})`}">
        <div class="bg-overlay bg-linear-gradient-2"></div>
        <div class="container">
            <div class="row justify-content-end">
                <div class="col-lg-4 col-md-6 col-12">
                    <div class="p-4 bg-white rounded shadow-md mx-auto w-100" style="max-width: 400px;">
                        <form>
                            <NuxtLink to="/"><img :src="logo" class="mb-4 d-block mx-auto" alt=""></NuxtLink>
                            <h6 class="mb-2 text-uppercase fw-semibold">Reset your password</h6>

                            <p class="text-muted">Please enter your email address. You will receive a link to create a new password via email.</p>
                        
                            <div class="mb-3">
                                <label class="form-label fw-semibold">Your Email</label>
                                <input name="email" id="email" type="email" class="form-control" placeholder="example@website.com">
                            </div>
            
                            <button class="btn btn-primary w-100" type="submit">Send</button>

                            <div class="col-12 text-center mt-3">
                                <span><span class="text-muted small me-2">Remember your password ? </span> <NuxtLink to="/login" class="text-dark fw-semibold small">Sign in</NuxtLink></span>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
</template>

<script setup>
import bg from '@/assets/images/hero/auth.jpg'
import logo from '@/assets/images/logo-dark.png'

</script>

// __Coral_v1.2.0/Next/Javascript/src/app/reset-password/page.jsx
import Image from 'next/image'
import Link from 'next/link'

export default function ResetPassword() {
  return (
    <>
        <section className="bg-home d-flex align-items-center" style={{backgroundImage:`url('/images/hero/auth.jpg')`, backgroundPosition:'center'}}>
            <div className="bg-overlay bg-linear-gradient-2"></div>
            <div className="container">
                <div className="row justify-content-end">
                    <div className="col-lg-4 col-md-6 col-12">
                        <div className="p-4 bg-white rounded shadow-md mx-auto w-100" style={{maxWidth: '400px'}}>
                            <form>
                                <Link href="/"><Image src='/images/logo-dark.png' width={93} height={22} className="mb-4 d-block mx-auto" alt=""/></Link>
                                <h6 className="mb-2 text-uppercase fw-semibold">Reset your password</h6>

                                <p className="text-muted">Please enter your email address. You will receive a link to create a new password via email.</p>
                            
                                <div className="mb-3">
                                    <label className="form-label fw-semibold">Your Email</label>
                                    <input name="email" id="email" type="email" className="form-control" placeholder="example@website.com"/>
                                </div>
                
                                <button className="btn btn-primary w-100" type="submit">Send</button>

                                <div className="col-12 text-center mt-3">
                                    <span><span className="text-muted small me-2">Remember your password ? </span> <Link href="/login" className="text-dark fw-semibold small">Sign in</Link></span>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>   
    </>
  )
}
