// __Coral_v1.2.0/Svelte/src/pages/inner-pages/services.svelte
<script>
    import Navlight from "../../components/navbar/navlight.svelte";
    import bg from "../../assets/images/hero/pages.jpg";
    import { Link } from "svelte-routing";
    import { servicesData } from "../../data/data";
    import CtaTwo from "../../components/cta/cta-two.svelte";
    import TeamOne from "../../components/team/team-one.svelte";
    import Footer from "../../components/footer.svelte";

</script>

<Navlight/>

<section class="bg-half-170 d-table w-100" style="background: url({bg}) center;">
    <div class="bg-overlay bg-gradient-overlay"></div>
    <div class="container">
        <div class="row mt-5 justify-content-center">
            <div class="col-12">
                <div class="title-heading text-center">
                    <h5 class="heading fw-semibold mb-0 sub-heading text-white title-dark">Services / Features</h5>
                </div>
            </div>
        </div>

        <div class="position-middle-bottom">
            <nav aria-label="breadcrumb" class="d-block">
                <ul class="breadcrumb breadcrumb-muted mb-0 p-0">
                    <li class="breadcrumb-item"><Link to="/">Coral</Link></li>
                    <li class="breadcrumb-item active" aria-current="page">Services</li>
                </ul>
            </nav>
        </div>
    </div>
</section>

<div class="position-relative">
    <div class="shape overflow-hidden text-white">
        <svg viewBox="0 0 2880 48" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M0 48H1437.5H2880V0H2160C1442.5 52 720 0 720 0H0V48Z" fill="currentColor"></path>
        </svg>
    </div>
</div>

<section class="section">
    <div class="container">
        <div class="row align-items-center g-4">
            {#each servicesData as item}
                <div class="col-lg-4 col-md-6 col-12">
                    <div class="position-relative features text-center rounded shadow p-4 pt-5">
                        <div class="position-relative d-flex justify-content-center">
                            <i data-feather={item.icon} class="fea icon-md text-primary z-1"></i>
                            <div class="feature-icon bg-soft-primary position-absolute top-0 translate-middle"></div>
                        </div>

                        <div class="mt-4">
                            <Link to="/service-detail" class="h5 text-dark link-title">{item.title}</Link>
                            <p class="text-muted mt-3">{item.desc}</p>
                            <Link to="/service-detail" class="text-primary">Learn More <i class="mdi mdi-arrow-right align-middle"></i></Link>
                        </div>
                    </div>
                </div>
            {/each}
        </div>
    </div>
</section>

<CtaTwo/>

<section class="section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12">
                <div class="section-title text-center mb-4 pb-2">
                    <h4 class="title mb-3">Our Minds</h4>
                    <p class="text-muted para-desc mx-auto mb-0">We've cultivated a dynamic space where creativity seamlessly intertwines with strategy and innovation.</p>
                </div>
            </div>
        </div>
        <TeamOne/>
    </div>
</section>

<Footer/>

// __Coral_v1.2.0/React/Javascript/src/pages/inner-pages/services.jsx
import { Link } from 'react-router-dom'

import bg from '../../assets/images/hero/pages.jpg'

import { servicesData } from '../../data/data'

import Navlight from '../../components/navbar/navlight'
import CtaThree from '../../components/cta/cta-three'
import TeamOne from '../../components/team/team-one'
import Footer from '../../components/footer'
import ScrollToTop from '../../components/scroll-to-top'

export default function Services() {
  return (
    <>
        <Navlight/>

        <section className="bg-half-170 d-table w-100" style={{backgroundImage:`url(${bg})`, backgroundPosition:'center'}}>
            <div className="bg-overlay bg-gradient-overlay"></div>
            <div className="container">
                <div className="row mt-5 justify-content-center">
                    <div className="col-12">
                        <div className="title-heading text-center">
                            <h5 className="heading fw-semibold mb-0 sub-heading text-white title-dark">Services / Features</h5>
                        </div>
                    </div>
                </div>

                <div className="position-middle-bottom">
                    <nav aria-label="breadcrumb" className="d-block">
                        <ul className="breadcrumb breadcrumb-muted mb-0 p-0">
                            <li className="breadcrumb-item"><Link to="/">Coral</Link></li>
                            <li className="breadcrumb-item active" aria-current="page">Services</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </section>
        <div className="position-relative">
            <div className="shape overflow-hidden text-white">
                <svg viewBox="0 0 2880 48" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M0 48H1437.5H2880V0H2160C1442.5 52 720 0 720 0H0V48Z" fill="currentColor"></path>
                </svg>
            </div>
        </div>

         <section className="section">
            <div className="container">
                <div className="row g-4">
                    {servicesData.map((item,index)=>{
                        let Icon = item.icon
                        return(
                            <div className="col-lg-4 col-md-6 col-12" key={index}>
                                <div className="position-relative features text-center rounded shadow p-4 pt-5">
                                    <div className="position-relative d-flex justify-content-center">
                                        <Icon className="fea icon-md text-primary z-1"></Icon>
                                        <div className="feature-icon bg-soft-primary position-absolute top-0 translate-middle"></div>
                                    </div>
            
                                    <div className="mt-4">
                                        <Link to="/service-detail" className="h5 text-dark link-title">{item.title}</Link>
                                        <p className="text-muted mt-3">{item.desc}</p>
                                        <Link to="/service-detail" className="text-primary">Learn More <i className="mdi mdi-arrow-right align-middle"></i></Link>
                                    </div>
                                </div>
                            </div>
                        )
                    })}
                </div>
            </div>
        </section>

        <CtaThree/>

        <section className="section">
            <div className="container">
                <div className="row justify-content-center">
                    <div className="col-12">
                        <div className="section-title text-center mb-4 pb-2">
                            <h4 className="title mb-3">Our Minds</h4>
                            <p className="text-muted para-desc mx-auto mb-0">We've cultivated a dynamic space where creativity seamlessly intertwines with strategy and innovation.</p>
                        </div>
                    </div>
                </div>
                <TeamOne/>
            </div>
        </section>
        <Footer/>

        <ScrollToTop/>
    </>
  )
}
