// __Coral_v1.2.0/Nuxt/app/pages/team.vue
<template>
    <div>
        <NavLight/>

        <section class="bg-half-170 d-table w-100" :style="{backgroundImage:`url(${bg})`, backgroundPosition:'center'}">
            <div class="bg-overlay bg-gradient-overlay"></div>
            <div class="container">
                <div class="row mt-5 justify-content-center">
                    <div class="col-12">
                        <div class="title-heading text-center">
                            <h5 class="heading fw-semibold mb-0 sub-heading text-white title-dark">Our Team Members</h5>
                        </div>
                    </div>
                </div>

                <div class="position-middle-bottom">
                    <nav aria-label="breadcrumb" class="d-block">
                        <ul class="breadcrumb breadcrumb-muted mb-0 p-0">
                            <li class="breadcrumb-item"><NuxtLink to="/">Coral</NuxtLink></li>
                            <li class="breadcrumb-item active" aria-current="page">Team</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </section>
        <div class="position-relative">
            <div class="shape overflow-hidden text-white">
                <svg viewBox="0 0 2880 48" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M0 48H1437.5H2880V0H2160C1442.5 52 720 0 720 0H0V48Z" fill="currentColor"></path>
                </svg>
            </div>
        </div>

        <section class="section">
            <div class="container">
                <div class="row g-4">
                    <div v-for="(item, index) in teamData" :key="index" class="col-lg-3 col-md-6 col-12">
                        <div class="card team team-primary bg-transparent text-center mb-5">
                            <div class="card-img team-image d-inline-block mx-auto rounded overflow-hidden">
                                <img :src="item.image" class="img-fluid" alt="">

                                <ul class="list-unstyled team-social mb-0">
                                    <li v-for="(el, index) in item.social" :key="index" class="mt-1"><NuxtLink to="#" class="btn btn-sm btn-pills btn-icon"><i :data-feather="el" class="icons fea-social"></i></NuxtLink></li>
                                </ul>
                            </div>

                            <div class="content bg-white mx-4 p-4 z-1 rounded shadow">
                                <NuxtLink to="#" class="text-dark h5 mb-0 title">{{item.name}}</NuxtLink>
                                <h6 class="text-muted mb-0 fw-normal">{{item.position}}</h6>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <FooterOne/>

        <ScrollToTop/>
    </div>
</template>

<script setup>
    import NavLight from '@/components/navbar/nav-light.vue';
    import bg from '@/assets/images/hero/pages.jpg';

    import { teamData } from '@/data/data';
</script>

// __Coral_v1.2.0/React/Javascript/src/pages/inner-pages/team.jsx
import { Link } from 'react-router-dom'

import bg from '../../assets/images/hero/pages.jpg'

import Navlight from '../../components/navbar/navlight'
import Footer from '../../components/footer'
import ScrollToTop from '../../components/scroll-to-top'

import { teamData } from '../../data/data'

export default function Team() {
  return (
    <>
        <Navlight/>


        <section className="bg-half-170 d-table w-100" style={{backgroundImage:`url(${bg})`, backgroundPosition:'center'}}>
            <div className="bg-overlay bg-gradient-overlay"></div>
            <div className="container">
                <div className="row mt-5 justify-content-center">
                    <div className="col-12">
                        <div className="title-heading text-center">
                            <h5 className="heading fw-semibold mb-0 sub-heading text-white title-dark">Our Team Members</h5>
                        </div>
                    </div>
                </div>

                <div className="position-middle-bottom">
                    <nav aria-label="breadcrumb" className="d-block">
                        <ul className="breadcrumb breadcrumb-muted mb-0 p-0">
                            <li className="breadcrumb-item"><Link to="/">Coral</Link></li>
                            <li className="breadcrumb-item active" aria-current="page">Team</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </section>

        <div className="position-relative">
            <div className="shape overflow-hidden text-white">
                <svg viewBox="0 0 2880 48" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M0 48H1437.5H2880V0H2160C1442.5 52 720 0 720 0H0V48Z" fill="currentColor"></path>
                </svg>
            </div>
        </div>

        <section className="section">
            <div className="container">
                <div className="row g-4">
                    {teamData.map((item,index)=>{
                        return(
                            <div className="col-lg-3 col-md-6 col-12" key={index}>
                                <div className="card team team-primary bg-transparent text-center mb-5">
                                    <div className="card-img team-image d-inline-block mx-auto rounded overflow-hidden">
                                        <img src={item.image} className="img-fluid" alt=""/>

                                        <ul className="list-unstyled team-social mb-0">
                                            {item.social.map((el,index)=>{
                                                let Icon = el
                                                return(
                                                    <li className="mt-1" key={index}><Link to="#" className="btn btn-sm btn-pills btn-icon"><Icon className="icons fea-social"></Icon></Link></li>
                                                )
                                            })}
                                        </ul>
                                    </div>

                                    <div className="content bg-white mx-4 p-4 z-1 rounded shadow">
                                        <Link to="#" className="text-dark h5 mb-0 title">{item.name}</Link>
                                        <h6 className="text-muted mb-0 fw-normal">{item.position}</h6>
                                    </div>
                                </div>
                            </div>
                        )
                    })}
                </div>
            </div>
        </section>

        <Footer/>

        <ScrollToTop/>
    </>
  )
}
