// __Coral_v1.2.0/React/Javascript/src/pages/index/index-minimal-portfolio.jsx
import { useState } from 'react'
import { Link } from 'react-router-dom'

import bg from '../../assets/images/hero/bg-squre.png'
import hero from '../../assets/images/logo-icon.png'

import { masonaryData } from '../../data/data'

import { Lightbox } from "yet-another-react-lightbox";
import "yet-another-react-lightbox/styles.css";

import { FiCamera } from 'react-icons/fi'

import Navdark from '../../components/navbar/navdark'
import Footer from '../../components/footer'
import ScrollToTop from '../../components/scroll-to-top'


export default function IndexMinimalPortfolio() {
    let [open, setOpen] = useState(false);
    let [isOpen, setIsOpen] = useState(false);
    let [currentImageIndex, setCurrentImageIndex] = useState(0);

     let handleImageClick = (index) => {
        setCurrentImageIndex(index);
        setOpen(true);
    };
    
    const slides = masonaryData.map((item) => ({ src: item.image }));

  return (
    <div id="boxed-layput" style={{backgroundImage:`url(${bg})`}}>
        <div className="boxed">
            <Navdark bg="boxed-home" position="nav-right" tagline=""/>
            <section className="section overflow-hidden">
                <div className="container">
                    <div className="row align-items-center g-4">
                        <div className="col-lg-7 col-md-6 order-2 order-md-1">
                            <div className="title-heading">
                                <h1 className="display-4 fw-bold mb-3">Discover top creative <br/> <span className="text-primary">talents</span> & <span className="text-primary">portfolios</span></h1>
                                <p className="para-desc text-muted mb-0">An independent design agency based in Newyork.</p>
                            </div>
                        </div>

                        <div className="col-lg-5 col-md-6 order-1 order-md-2">
                            <div className="position-relative">
                                <img src={hero} className="img-fluid opacity-25" alt=""/>
                                <div className="position-absolute top-50 start-50 translate-middle">
                                    <Link to="#" onClick={() => setIsOpen(!isOpen)} className="avatar avatar-md-md rounded-pill shadow bg-primary d-flex justify-content-center align-items-center lightbox">
                                        <i className="mdi mdi-play mdi-24px text-white"></i>
                                    </Link>
                                </div>

                                {isOpen &&
                                    <div className="modal show d-block " tabIndex="-1" style={{ backgroundColor: '#00000099' }}>
                                        <div className="modal-dialog modal-dialog-centered modal-lg position-relative">
                                            <div className="modal-content">
                                                <div className="modal-header py-2">
                                                    <button type="button" className="btn-close" aria-label="Close" onClick={() => setIsOpen(!isOpen)}></button>
                                                </div>
                                                <div className="modal-body p-2">
                                                    <div className="ratio ratio-16x9">
                                                        <iframe src="https://www.youtube.com/embed/yba7hPeTSjk?playlist=yba7hPeTSjk&loop=1" title="YouTube video" allowFullScreen ></iframe>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            <section className="section pt-1">
                <div className="container">
                    <div className="column-4 gap-0" id="grid ">
                        {masonaryData.map((item,index)=>( 
                            <div className="" key={index}>
                                <div className="portfolio masonry position-relative overflow-hidden">
                                    <div className="position-relative overflow-hidden image">
                                        <img src={item.image} className="img-fluid" alt=""/>
                                        <div className="position-absolute start-0 end-0 top-0 bottom-0 overlay rounded bg-black m-4"></div>
                                    </div>

                                    <div className="content">
                                        <div className="title-body p-3 position-absolute start-0 end-0 m-4">
                                            <a href="" className="link-title text-white fs-5 fw-medium">Artboard Studio</a>
                                            <p className="text-white-50 mb-0">Custom Branding</p>
                                        </div>

                                        <div className="p-3 position-absolute top-0 end-0 m-4">
                                            <Link to="#" onClick={()=>handleImageClick(item.id - 1)} className="btn btn-sm btn-icon btn-pills btn-primary lightbox"><FiCamera className="fea icon-sm"/></Link>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        ))}
                    </div>
                    <Lightbox
                        open={open}
                        index={currentImageIndex}
                        close={() => setOpen(false)}
                        slides={slides}
                    />

                    <div className="row">
                        <div className="col">
                            <div className="mt-4 text-center">
                                <Link to="#" className="btn btn-primary">See more works <i className="mdi mdi-arrow-right"></i></Link>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <Footer/>
            <ScrollToTop/>
        </div>
    </div>
  )
}

// __Coral_v1.2.0/Svelte/src/pages/index/index-minimal-portfolio.svelte
<script>
// @ts-nocheck

    import Navdark from "../../components/navbar/navdark.svelte";
    import bg from '../../assets/images/hero/bg-squre.png'
    import logo from '../../assets/images/logo-icon.png'
    import { masonaryData } from "../../data/data";
    import Footer from "../../components/footer.svelte";

    import Tobii from 'tobii';
    import { onMount } from "svelte";

    let tobii;

    onMount(() => {
        tobii = new Tobii();
    });
    
</script>

<div id="boxed-layput" style="background: url({bg});">
    <div class="boxed">
        <Navdark/>

        <section class="section overflow-hidden">
            <div class="container">
                <div class="row align-items-center g-4">
                    <div class="col-lg-7 col-md-6 order-2 order-md-1">
                        <div class="title-heading">
                            <h1 class="display-4 fw-bold mb-3">Discover top creative <br> <span class="text-primary">talents</span> & <span class="text-primary">portfolios</span></h1>
                            <p class="para-desc text-muted mb-0">An independent design agency based in Newyork.</p>
                        </div>
                    </div>

                    <div class="col-lg-5 col-md-6 order-1 order-md-2">
                        <div class="position-relative">
                            <img src={logo} class="img-fluid opacity-25" alt="">
                            <div class="position-absolute top-50 start-50 translate-middle">
                                <a href="#!" data-type="youtube" data-id="yba7hPeTSjk" aria-label="link" class="avatar avatar-md-md rounded-pill shadow bg-primary d-flex justify-content-center align-items-center lightbox">
                                    <i class="mdi mdi-play mdi-24px text-white"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <section class="section pt-1">
            <div class="container">
                <div class="column-4 gap-0" id="grid">
                    {#each masonaryData as item}
                        <div class="">
                            <div class="portfolio masonry position-relative overflow-hidden">
                                <div class="position-relative overflow-hidden image">
                                    <img src={item.image} class="img-fluid" alt="">
                                    <div class="position-absolute start-0 end-0 top-0 bottom-0 overlay rounded bg-black m-4"></div>
                                </div>

                                <div class="content">
                                    <div class="title-body p-3 position-absolute start-0 end-0 m-4">
                                        <a href="#!" class="link-title text-white fs-5 fw-medium">Artboard Studio</a>
                                        <p class="text-white-50 mb-0">Custom Branding</p>
                                    </div>

                                    <div class="p-3 position-absolute top-0 end-0 m-4">
                                        <a href={item.image} class="btn btn-sm btn-icon btn-pills btn-primary lightbox" aria-label="link"><i data-feather="camera" class="fea icon-sm"></i></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {/each}
                </div>

                <div class="row">
                    <div class="col">
                        <div class="mt-4 text-center">
                            <a href="#!" class="btn btn-primary">See more works <i class="mdi mdi-arrow-right"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <Footer/>
    </div>
</div>
