// src/components/blog/blog-desc.vue
<template>
    <div class="card-body">
        <p class="text-muted">The most well-known dummy text is the 'Lorem Ipsum', which is said to have originated in the 16th century. Lorem Ipsum is composed in a pseudo-Latin language which more or less corresponds to 'proper' Latin. It contains a series of real Latin words. This ancient dummy text is also incomprehensible, but it imitates the rhythm of most European languages in Latin script. The advantage of its Latin origin and the relative meaninglessness of Lorum Ipsum is that the text does not attract attention to itself or distract the viewer's attention from the layout.</p>
        <p class="text-muted">Thus, Lorem Ipsum has only limited suitability as a visual filler for German texts. If the fill text is intended to illustrate the characteristics of different typefaces, it sometimes makes sense to select texts containing the various letters and symbols specific to the output language.</p>
    
        <blockquote class="text-center mx-auto blockquote"><i class="mdi mdi-format-quote-open mdi-48px text-muted opacity-2 d-block"></i> The man who comes back through the door in the wall will never be quite the same as the man who went out. <small class="d-block text-muted mt-2">- Coral Template</small></blockquote>
    
        <p class="text-muted">There is now an abundance of readable dummy texts. These are usually used when a text is required purely to fill a space. These alternatives to the classic Lorem Ipsum texts are often amusing and tell short, funny or nonsensical stories.</p>
    
        <router-link to="#" class="badge badge-link bg-primary">Minimal</router-link>
        <router-link to="#" class="badge badge-link bg-primary mx-1">Interior</router-link>
        <router-link to="#" class="badge badge-link bg-primary">Furniture</router-link>
    </div>
</template>

<script setup>
   
</script>

// __Coral_v1.2.0/React/Typescript/src/components/blog/blog-desc.tsx
import { Link } from 'react-router-dom'

export default function BlogDesc() {
  return (
    <>
        <div className="card-body">
            <p className="text-muted">The most well-known dummy text is the 'Lorem Ipsum', which is said to have originated in the 16th century. Lorem Ipsum is composed in a pseudo-Latin language which more or less corresponds to 'proper' Latin. It contains a series of real Latin words. This ancient dummy text is also incomprehensible, but it imitates the rhythm of most European languages in Latin script. The advantage of its Latin origin and the relative meaninglessness of Lorum Ipsum is that the text does not attract attention to itself or distract the viewer's attention from the layout.</p>
            <p className="text-muted">Thus, Lorem Ipsum has only limited suitability as a visual filler for German texts. If the fill text is intended to illustrate the characteristics of different typefaces, it sometimes makes sense to select texts containing the various letters and symbols specific to the output language.</p>
        
            <blockquote className="text-center mx-auto blockquote"><i className="mdi mdi-format-quote-open mdi-48px text-muted opacity-2 d-block"></i> The man who comes back through the door in the wall will never be quite the same as the man who went out. <small className="d-block text-muted mt-2">- Coral Template</small></blockquote>
        
            <p className="text-muted">There is now an abundance of readable dummy texts. These are usually used when a text is required purely to fill a space. These alternatives to the classic Lorem Ipsum texts are often amusing and tell short, funny or nonsensical stories.</p>
        
            <Link to="#" className="badge badge-link bg-primary">Minimal</Link>
            <Link to="#" className="badge badge-link bg-primary mx-1">Interior</Link>
            <Link to="#" className="badge badge-link bg-primary">Furniture</Link>
        </div>   
    </>
  )
}
