// __Coral_v1.2.0/Gatsby/src/components/blog/blog-one.jsx
import React from 'react'
import { blogData } from '../../data/data'
import { Link } from 'gatsby'

export default function BlogOne() {
  return (
    <div className="row g-4">
        {blogData.slice(0,3).map((item,index)=>( 
            <div className="col-lg-4 col-md-6 col-12" key={index}>
                <div className="blog position-relative overflow-hidden shadow rounded p-4">
                    <div className="position-relative">
                        <div className="blog-image position-relative overflow-hidden rounded shadow">
                            <img src={item.image} className="img-fluid" alt=""/>
                        </div>

                        <div className="position-absolute top-100 start-0 translate-middle-y ms-2">
                            <Link to="#" className="badge bg-primary">{item.tag}</Link>
                        </div>
                    </div>

                    <div className="pt-4">
                        <Link to={`/blog-standard-post/${item.id}`} className="text-dark title h5">{item.title}</Link>
                        <p className="text-muted my-2">{item.desc}</p>
                        <Link to={`/blog-standard-post/${item.id}`} className="text-dark read-more">Read More <i className="mdi mdi-chevron-right align-middle"></i></Link>
                    </div>
                </div>
            </div>
        ))}
    </div>
  )
}

// src/components/blog/blog-one.vue
<template>
    <div class="row g-4">
        <div v-for="(item, index) in blogData.slice(0,3)" :key="index" class="col-lg-4 col-md-6 col-12">
            <div class="blog position-relative overflow-hidden shadow rounded p-4">
                <div class="position-relative">
                    <div class="blog-image position-relative overflow-hidden rounded shadow">
                        <img :src="item.image" class="img-fluid" alt="">
                    </div>

                    <div class="position-absolute top-100 start-0 translate-middle-y ms-2">
                        <router-link to="#" class="badge bg-primary">{{item.tag}}</router-link>
                    </div>
                </div>

                <div class="pt-4">
                    <router-link to="/blog-standard-post" class="text-dark title h5">{{item.title}}</router-link>

                    <p class="text-muted my-2">{{item.desc}}</p>

                    <router-link to="/blog-standard-post" class="text-dark read-more">Read More <i class="mdi mdi-chevron-right align-middle"></i></router-link>
                </div>
            </div>
        </div>
    </div>
</template>

<script setup>
    import { blogData } from '@/data/data';
</script>

<style lang="scss" scoped>

</style>
