// src/pages/auth/reset-password.vue
<template>
    <section class="bg-home d-flex align-items-center" :style="{backgroundImage:`url(${bg})`}">
        <div class="bg-overlay bg-linear-gradient-2"></div>
        <div class="container">
            <div class="row justify-content-end">
                <div class="col-lg-4 col-md-6 col-12">
                    <div class="p-4 bg-white rounded shadow-md mx-auto w-100" style="max-width: 400px;">
                        <form>
                            <router-link to="/"><img :src="logo" class="mb-4 d-block mx-auto" alt=""></router-link>
                            <h6 class="mb-2 text-uppercase fw-semibold">Reset your password</h6>

                            <p class="text-muted">Please enter your email address. You will receive a link to create a new password via email.</p>
                        
                            <div class="mb-3">
                                <label class="form-label fw-semibold">Your Email</label>
                                <input name="email" id="email" type="email" class="form-control" placeholder="example@website.com">
                            </div>
            
                            <button class="btn btn-primary w-100" type="submit">Send</button>

                            <div class="col-12 text-center mt-3">
                                <span><span class="text-muted small me-2">Remember your password ? </span> <router-link to="/login" class="text-dark fw-semibold small">Sign in</router-link></span>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
</template>

<script setup>
import bg from '@/assets/images/hero/auth.jpg'
import logo from '@/assets/images/logo-dark.png'

</script>

// __Coral_v1.2.0/Svelte/src/pages/auth/reset-password.svelte
<script>
    import { Link } from 'svelte-routing';
    import bg from '../../assets/images/hero/auth.jpg'
    import logo from '../../assets/images/logo-dark.png'
</script>

<section class="bg-home d-flex align-items-center" style="background: url({bg}) center;">
    <div class="bg-overlay bg-linear-gradient-2"></div>
    <div class="container">
        <div class="row justify-content-end">
            <div class="col-lg-4 col-md-6 col-12">
                <div class="p-4 bg-white rounded shadow-md mx-auto w-100" style="max-width: 400px;">
                    <form>
                        <Link to="/"><img src={logo} class="mb-4 d-block mx-auto" alt=""></Link>
                        <h6 class="mb-2 text-uppercase fw-semibold">Reset your password</h6>

                        <p class="text-muted">Please enter your email address. You will receive a link to create a new password via email.</p>
                    
                        <div class="mb-3">
                            <label class="form-label fw-semibold" for="mail">Your Email</label>
                            <input name="email" id="email" type="email" class="form-control" placeholder="example@website.com">
                        </div>
        
                        <button class="btn btn-primary w-100" type="submit">Send</button>

                        <div class="col-12 text-center mt-3">
                            <span><span class="text-muted small me-2">Remember your password ? </span> <Link to="/login" class="text-dark fw-semibold small">Sign in</Link></span>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
