// __Coral_v1.2.0/Nuxt/app/pages/testimonial.vue
<template>
    <div>
        <NavLight/>

        <section class="bg-half-170 d-table w-100" :style="{backgroundImage:`url(${bg})`}">
            <div class="bg-overlay bg-gradient-overlay"></div>
            <div class="container">
                <div class="row mt-5 justify-content-center">
                    <div class="col-12">
                        <div class="title-heading text-center">
                            <h5 class="heading fw-semibold mb-0 sub-heading text-white title-dark">Testimonial</h5>
                        </div>
                    </div>
                </div>

                <div class="position-middle-bottom">
                    <nav aria-label="breadcrumb" class="d-block">
                        <ul class="breadcrumb breadcrumb-muted mb-0 p-0">
                            <li class="breadcrumb-item"><NuxtLink to="/">Coral</NuxtLink></li>
                            <li class="breadcrumb-item active" aria-current="page">Testimonial</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </section>

        <div class="position-relative">
            <div class="shape overflow-hidden text-white">
                <svg viewBox="0 0 2880 48" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M0 48H1437.5H2880V0H2160C1442.5 52 720 0 720 0H0V48Z" fill="currentColor"></path>
                </svg>
            </div>
        </div>

        <section class="section">
            <div class="container">
                <div class="column-3">
                    <div v-for="(item, index) in clientData" :key="index" class="col-12 mb-3">
                        <div class="position-relative overflow-hidden z-1 bg-white rounded shadow p-4">
                            <div class="d-flex align-items-center justify-content-between">
                                <h6 class="mb-0">{{item.tag}}</h6>

                                <ul class="list-unstyled mb-0 text-warning">
                                    <li v-for="(el, index) in item.rate" :key="index" class="list-inline-item"><i :class="el"></i></li>
                                </ul>
                            </div>

                            <p class="text-muted fst-italic mt-2">{{item.desc}}</p>

                            <div class="d-flex align-items-center">
                                <img :src="item.image" class="avatar avatar-small rounded-pill shadow" alt="">
                                <div class="ms-2">
                                    <h6 class="text-dark small mb-0">{{item.name}}</h6>
                                    <small class="text-muted d-block">{{item.position}}</small>
                                </div>
                            </div>

                            <i class="mdi mdi-format-quote-open text-primary position-absolute top-50 start-50 translate-middle z-n1 testi-icon"></i>
                        </div>
                    </div>
                </div>
                

                <div class="row justify-content-center">
                    <div class="col mt-4">
                        <div class="text-center">
                            <NuxtLink to="#" class="text-primary">See More <i class="mdi mdi-chevron-right"></i></NuxtLink>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <FooterOne/>

        <ScrollToTop/>
    </div>

    
</template>

<script setup>
    import bg from '@/assets/images/hero/pages.jpg'
    import NavLight from '@/components/navbar/nav-light.vue';
    import { clientData } from '@/data/data';
</script>

// __Coral_v1.2.0/React/Typescript/src/pages/inner-pages/testimonial.tsx
import { Link } from 'react-router-dom'
import bg from '../../assets/images/hero/pages.jpg'

import { clientData } from '../../data/data'

import Navlight from '../../components/navbar/navlight'
import Footer from '../../components/footer'
import ScrollToTop from '../../components/scroll-to-top'

interface ClientData{
    tag: string;
    image: string;
    rate: string[];
    desc: string;
    name: string;
    position: string;
}

export default function Testimonial() {
  return (
    <>
        <Navlight/>

        <section className="bg-half-170 d-table w-100" style={{backgroundImage:`url(${bg})`, backgroundPosition:'center'}}>
            <div className="bg-overlay bg-gradient-overlay"></div>
            <div className="container">
                <div className="row mt-5 justify-content-center">
                    <div className="col-12">
                        <div className="title-heading text-center">
                            <h5 className="heading fw-semibold mb-0 sub-heading text-white title-dark">Testimonial</h5>
                        </div>
                    </div>
                </div>

                <div className="position-middle-bottom">
                    <nav aria-label="breadcrumb" className="d-block">
                        <ul className="breadcrumb breadcrumb-muted mb-0 p-0">
                            <li className="breadcrumb-item"><Link to="/">Coral</Link></li>
                            <li className="breadcrumb-item active" aria-current="page">Testimonial</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </section>

        <div className="position-relative">
            <div className="shape overflow-hidden text-white">
                <svg viewBox="0 0 2880 48" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M0 48H1437.5H2880V0H2160C1442.5 52 720 0 720 0H0V48Z" fill="currentColor"></path>
                </svg>
            </div>
        </div>   

        <section className="section">
            <div className="container">
                <div className="column-3">
                    {clientData.map((item:ClientData,index:number)=>{
                        return(
                            <div className="mb-3" key={index}>
                                <div className="position-relative overflow-hidden z-1 bg-white rounded shadow p-4">
                                    <div className="d-flex align-items-center justify-content-between">
                                        <h6 className="mb-0">{item.tag}</h6>

                                        <ul className="list-unstyled mb-0 text-warning">
                                            {item.rate.map((el,index)=>(
                                                <li className="list-inline-item" key={index}><i className={el}></i></li>
                                            ))}
                                        </ul>
                                    </div>

                                    <p className="text-muted fst-italic mt-2">{item.desc}</p>

                                    <div className="d-flex align-items-center">
                                        <img src={item.image} className="avatar avatar-small rounded-pill shadow" alt=""/>
                                        <div className="ms-2">
                                            <h6 className="text-dark small mb-0">{item.name}</h6>
                                            <small className="text-muted d-block">{item.position}</small>
                                        </div>
                                    </div>

                                    <i className="mdi mdi-format-quote-open text-primary position-absolute top-50 start-50 translate-middle z-n1 testi-icon"></i>
                                </div>
                            </div>
                        )
                    })}
                </div>

                <div className="row justify-content-center">
                    <div className="col mt-4">
                        <div className="text-center">
                            <Link to="#" className="text-primary">See More <i className="mdi mdi-chevron-right"></i></Link>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <Footer/>

        <ScrollToTop/>
    </>
  )
}
