// src/components/scroll-to-top.vue
<template>
    <router-link to="#"  id="back-to-top" @click="scrollToTop" class="back-to-top rounded fs-5" :class="scroll ? 'd-block' : 'd-none'"><i data-feather="arrow-up" class="fea icon-sm align-middle"></i></router-link>
</template>

<script setup>

    import { onMounted, ref } from 'vue';

    const scroll = ref(false)

    const scrollToTop = () =>{
        window.scrollTo({ top: 0, behavior: 'smooth' });
    }

    const handleScroll = () => {
        if (window.scrollY >= 50) {
            scroll.value = true
        } else {
            scroll.value = false
        }
    }

    onMounted(()=>{
		window.addEventListener('scroll', handleScroll);
	})
</script>

// __Coral_v1.2.0/Gatsby/src/components/scroll-to-top.jsx
import { Link } from 'gatsby';
import React,{ useEffect, useState } from 'react';
import { FiArrowUp } from 'react-icons/fi'

export default function ScrollToTop() {
     let [scrolling, setScrolling] = useState(false);

    useEffect(()=>{

        const handleScroll = () => {
            const isScrolling = window.scrollY > 50;
            setScrolling(isScrolling);
        };
        window.addEventListener('scroll', handleScroll);

        return()=>{
            window.removeEventListener('scroll', handleScroll);
        }
        
    },[])

    const scrollToTop = () =>{ 
        window.scrollTo({ 
          top: 0,  
          behavior: 'smooth'
        }); 
    }; 
  return (
    <>
        {scrolling && 
            (<Link to="#" onClick={()=>scrollToTop()} className="back-to-top rounded fs-5 d-block"><FiArrowUp data-feather="arrow-up" className="fea icon-sm align-middle"/></Link>)
        }
    </>
  )
}
