// __Coral_v1.2.0/Svelte/src/pages/blog/blog-link-post.svelte
<script>
    import Navlight from "../../components/navbar/navlight.svelte";
    import bg from '../../assets/images/hero/pages.jpg'
    import { Link } from "svelte-routing";
    import SidebarBlog from "../../components/blog/sidebar-blog.svelte";
    import BlogComment from "../../components/blog/blog-comment.svelte";
    import BlogDesc from "../../components/blog/blog-desc.svelte";
    import Footer from "../../components/footer.svelte";
    import bg1 from '../../assets/images/blog/1.jpg'
    import bg2 from '../../assets/images/blog/2.jpg'
    import bg3 from '../../assets/images/blog/3.jpg'
</script>

<Navlight/>

<section class="bg-half-170 d-table w-100" style="background: url({bg}) center;">
    <div class="bg-overlay bg-gradient-overlay"></div>
    <div class="container">
        <div class="row mt-5 justify-content-center">
            <div class="col-12">
                <div class="title-heading text-center">
                    <span class="badge bg-primary">Coral</span>
                    <h5 class="heading fw-semibold mb-0 sub-heading text-white title-dark mt-4">Coral - Multipurpose Template</h5>

                    <ul class="list-inline text-center mb-0">
                        <li class="list-inline-item mx-4 mt-4">
                            <span class="text-white-50 d-block">Author</span>
                            <a href="#!" class="text-white title-dark">Coral</a>
                        </li>

                        <li class="list-inline-item mx-4 mt-4">
                            <span class="text-white-50 d-block">Date</span>
                            <span class="text-white title-dark">15th July 2025</span>
                        </li>

                        <li class="list-inline-item mx-4 mt-4">
                            <span class="text-white-50 d-block">Read Time</span>
                            <span class="text-white title-dark">5 min read</span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="position-middle-bottom">
            <nav aria-label="breadcrumb" class="d-block">
                <ul class="breadcrumb breadcrumb-muted mb-0 p-0">
                    <li class="breadcrumb-item"><Link to="/">Coral</Link></li>
                    <li class="breadcrumb-item"><Link to="/blogs">Blogs</Link></li>
                    <li class="breadcrumb-item active" aria-current="page">Coral - Multipurpose Template</li>
                </ul>
            </nav>
        </div>
    </div>
</section>
<div class="position-relative">
    <div class="shape overflow-hidden text-white">
        <svg viewBox="0 0 2880 48" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M0 48H1437.5H2880V0H2160C1442.5 52 720 0 720 0H0V48Z" fill="currentColor"></path>
        </svg>
    </div>
</div>

<section class="section">
    <div class="container">
        <div class="row g-4">
            <div class="col-lg-8 col-md-7 mt-0">
               
                <div class="card text-center border-0 shadow rounded overflow-hidden mt-4">
                    <div class="card-body">
                        <div class="bg-soft-primary rounded-3 p-4 mb-4">
                            <a href="#!" class="tag h6 text-decoration-underline">Templates & Themes</a>
                            <div class="position-relative my-3">
                                <div class="p-3 rounded-circle d-inline-flex bg-white"><i class="mdi mdi-36px mdi-link-variant lh-1"></i></div>
                            </div>


                            <a href="#!" class="title h4 text-dark">Coral - Multipurpose Template</a>
                            <p class="text-muted para-desc mx-auto mt-2">If the distribution of letters and 'words' is random, the reader will not be distracted from making a neutral judgement on the visual impact and readability of the typefaces.</p>
                            
                            <span class="text-muted mb-0">15th July 2025</span>
                        </div>

                        <BlogDesc/>
                    </div>
                </div>
                <BlogComment/>
            </div>

            <div class="col-lg-4 col-md-5 col-12">
                <SidebarBlog/>
            </div>
        </div>
    </div>
</section>

<Footer/>

// __Coral_v1.2.0/Next/Typescript/src/app/blog-link-post/page.tsx
import React from 'react'
import Link from 'next/link'

import Navlight from '../components/navbar/navlight'
import BlogDesc from '../components/blog/blog-desc'
import BlogComment from '../components/blog/blog-comment'
import SidebarBlog from '../components/blog/sidebar-blog'
import Footer from '../components/footer'
import ScrollToTop from '../components/scroll-to-top'

export default function BlogLinkPost() {
  return (
    <>
        <Navlight/>

        <section className="bg-half-170 d-table w-100" style={{backgroundImage:`url('/images/hero/pages.jpg')`, backgroundPosition:'center'}}>
            <div className="bg-overlay bg-gradient-overlay"></div>
            <div className="container">
                <div className="row mt-5 justify-content-center">
                    <div className="col-12">
                        <div className="title-heading text-center">
                            <span className="badge bg-primary">Templates & Themes</span>
                            <h5 className="heading fw-semibold mb-0 sub-heading text-white title-dark mt-4">Coral - Multipurpose Template</h5>

                            <ul className="list-inline text-center mb-0">
                                <li className="list-inline-item mx-4 mt-4">
                                    <span className="text-white-50 d-block">Author</span>
                                    <Link href="#" className="text-white title-dark">Coral</Link>
                                </li>

                                <li className="list-inline-item mx-4 mt-4">
                                    <span className="text-white-50 d-block">Date</span>
                                    <span className="text-white title-dark">15th July 2025</span>
                                </li>

                                <li className="list-inline-item mx-4 mt-4">
                                    <span className="text-white-50 d-block">Read Time</span>
                                    <span className="text-white title-dark">5 min read</span>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>

                <div className="position-middle-bottom">
                    <nav aria-label="breadcrumb" className="d-block">
                        <ul className="breadcrumb breadcrumb-muted mb-0 p-0">
                            <li className="breadcrumb-item"><Link href="/">Coral</Link></li>
                            <li className="breadcrumb-item"><Link href="/blogs">Blogs</Link></li>
                            <li className="breadcrumb-item active" aria-current="page">Coral - Multipurpose Template</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </section>
        <div className="position-relative">
            <div className="shape overflow-hidden text-white">
                <svg viewBox="0 0 2880 48" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M0 48H1437.5H2880V0H2160C1442.5 52 720 0 720 0H0V48Z" fill="currentColor"></path>
                </svg>
            </div>
        </div>

        <section className="section">
            <div className="container">
                <div className="row g-4">
                    <div className="col-lg-8 col-md-7">
                        <div className="card text-center border-0 shadow rounded overflow-hidden">
                            <div className="card-body">
                                <div className="bg-soft-primary rounded-3 p-4 mb-4">
                                    <Link href="#!" className="tag h6 text-decoration-underline">Templates & Themes</Link>
                                    <div className="position-relative my-3">
                                        <div className="p-3 rounded-circle d-inline-flex bg-white"><i className="mdi mdi-36px mdi-link-variant lh-1"></i></div>
                                    </div>

                                    <Link href="#!" className="title h4 text-dark">Coral - Multipurpose Template</Link>
                                    <p className="text-muted para-desc mx-auto mt-2">If the distribution of letters and 'words' is random, the reader will not be distracted from making a neutral judgement on the visual impact and readability of the typefaces.</p>
                                    
                                    <span className="text-muted mb-0">15th July 2025</span>
                                </div>
                                
                                <BlogDesc/>
                            </div>
                        </div>

                        <BlogComment/>
                    </div>

                    <div className="col-lg-4 col-md-5 col-12">
                        <SidebarBlog/>
                    </div>
                </div>
            </div>
        </section>

        <Footer/>

        <ScrollToTop/>   
    </>
  )
}
